
sp.ids <- list(

 

    ##   Pseudopanurgus_piercei_f= list(Genus="Pseudopanurgus",
    ##                                   SubGenus ="",
    ##                                   Species="piercei",
    ##                                   SubSpecies="",
    ##                                   Sex="f", Author = "Crawford",
    ##                                   Determiner="",
    ##                                   temp.id= c()),


       Pseudopanurgus_atricornis_f= list(Genus="Pseudopanurgus",
                                      SubGenus ="",
                                      Species="atricornis",
                                      SubSpecies="",
                                      Sex="f", Author = "Cresson",
                                      Determiner="J.L. Neff",
                                      temp.id= c(37976, 37871, 37872, 37874, 37388,
                                                37697, 37694, 37185, 37736, 38342,
                                                37643)),


    Pseudopanurgus_atricornis_m= list(Genus="Pseudopanurgus",
                                      SubGenus ="",
                                      Species="atricornis",
                                      SubSpecies="",
                                      Sex="m", Author = "Cresson",
                                      Determiner="J.L. Neff",
                                      temp.id= c(37190, 37186, 37873,
                                                 37765, 37662, 37290,
                                                 37560, 37660,
                                                 37640, 37664, 37836,
                                                 37559)),


    Pseudopanurgus_albitarsis_f= list(Genus="Pseudopanurgus", SubGenus ="",
                                      Species="albitarsis",
                                      SubSpecies="",
                                      Sex="f", Author = "Cresson, 1872",
                                      Determiner="J.L. Neff",
                                      temp.id= c(38019, 38143,
                                                 38188, 38141, 38189,
                                                 38184, 38012,
                                                 38124, 38052)),



    Pseudopanurgus_albitarsis_m= list(Genus="Pseudopanurgus", SubGenus ="",
                                      Species="albitarsis",
                                      SubSpecies="",
                                      Sex="m", Author = "Cresson, 1872",
                                      Determiner="J.L. Neff",
                                      temp.id= c( 38228, 38144, 38013,
                                                 38057, 38049, 38193,
                                                 38231, 38017, 38055,
                                                 38048,
                                                 38128, 
                                                 38186, 
                                                 38147)),

    ##   Panurginus_cressoniellus_f= list(Genus="Panurginus", SubGenus ="",
    ##                                  Species="cressoniellus",
    ##                                  SubSpecies="",
    ##                                  Sex="f", Author = "Cockerell",
    ##                                  Determiner=,
    ##                                  temp.id= c()),


    ## Protandrena_sp_a= list(Genus="Protandrena", SubGenus ="",
    ##                        Species="sp.",
    ##                        SubSpecies="a",
    ##                        Sex="f", Author = "",
    ##                        Determiner=,
    ##                        temp.id= c()),


    ## Protandrena_sp_c= list(Genus="Protandrena", SubGenus ="",
    ##                        Species="sp.",
    ##                        SubSpecies="c",
    ##                        Sex="m", Author = "",
    ##                        Determiner="",
    ##                        temp.id= c()),

    ##     Protandrena_sp_d= list(Genus="Protandrena", SubGenus ="",
    ##                        Species="sp.",
    ##                        SubSpecies="d",
    ##                        Sex="f", Author = "",
    ##                        Determiner="",
    ##                        temp.id= c()),

    ##   Protandrena_sp_d= list(Genus="Protandrena", SubGenus ="",
    ##                        Species="sp.",
    ##                        SubSpecies="d",
    ##                        Sex="m", Author = "",
    ##                        Determiner="D. Yanega",
    ##                        temp.id= c()),

    ##   Protandrena_sp_d= list(Genus="Protandrena", SubGenus ="",
    ##                        Species="sp.",
    ##                        SubSpecies="e",
    ##                        Sex="m", Author = "",
    ##                        Determiner="",
    ##                        temp.id= c()),



    ## Pseudopanurgus_porterae_f= list(Genus="Pseudopanurgus",
    ##                             SubGenus ="",
    ##                             Species="porterae",
    ##                             SubSpecies="",
    ##                             Sex="f",
    ##                             Author = "Cockerell",
    ##                             Determiner="",
    ##                             temp.id= c()),



    ## Pseudopanurgus_porterae_m= list(Genus="Pseudopanurgus",
    ##                             SubGenus ="",
    ##                             Species="porterae",
    ##                             SubSpecies="",
    ##                             Sex="m",
    ##                             Author = "Cockerell",
    ##                             Determiner="",
    ##                             temp.id= c()),


    ## Andrena_argemonis_f = list(Genus="Andrena",
    ##                            SubGenus="Plastandrena",
    ##                            Species="argemonis",
    ##                            SubSpecies="",
    ##                            Sex="f", Author = "Cockerell",
    ##                            Determiner="",
    ##                            temp.id= c()),

    ## Andrena_argemonis_m = list(Genus="Andrena",
    ##                            SubGenus="Plastandrena",
    ##                            Species="argemonis",
    ##                            SubSpecies="",
    ##                            Sex="m", Author = "Cockerell",
    ##                            Determiner="",
    ##                            temp.id= c()),



       Heterosarus_bakeri_f= list(Genus="Heterosarus",
                               SubGenus ="",
                               Species="bakeri",
                               SubSpecies="",
                               Sex="f",
                               Author = "Cockerell",
                               Determiner="J.L. Neff",
                               temp.id= c(37365, 38339, 37652, 38332, 38333,
                                         38383, 38384, 38354)),

     Heterosarus_bakeri_m= list(Genus="Heterosarus",
                                SubGenus ="",
                                Species="bakeri",
                                SubSpecies="",
                                Sex="m",
                                Author = "Cockerell",
                                Determiner="J.L. Neff",
                                temp.id= c(36977, 37366)),


    ## Heterosarus_neomex_f= list(Genus="Heterosarus",
    ##                            SubGenus ="",
    ##                            Species="neomexicanus",
    ##                            SubSpecies="",
    ##                            Sex="f",
    ##                            Author = "Cockerell",
    ##                            Determiner="",
    ##                            temp.id= c()),

    ## Panurginus_sp_a_f= list(Genus="Panurginus", SubGenus ="",
    ##                         Species="sp.",
    ##                         SubSpecies="a",
    ##                         Sex="f", Author = "",
    ##                         Determiner="",
    ##                         temp.id= c()),

    ## Panurginus_cressoniellus_f= list(Genus="Panurginus",
    ##                                  SubGenus ="",
    ##                                  Species="cressoniellus",
    ##                                  SubSpecies="",
    ##                                  Sex="f", Author = "Cockerell",
    ##                                  Determiner="",
    ##                                  temp.id= c()),

   

    Andrena_apacheorum_f= list(Genus="Andrena",
                               SubGenus ="Cnemidandrena",
                               Species="apacheorum",
                               SubSpecies="",
                               Sex="f",
                               Author = "Cockerell",
                               Determiner="J.L. Neff",
                               temp.id= c(37693, 36706, 38064, 36481, 37561,
                                          37187, 37193, 37463, 37392, 37475,
                                          37044, 36503, 36773, 36914, 36697,
                                          37101, 37078, 37692, 36877, 37411,
                                          37401, 37295)),

    Andrena_apacheorum_m= list(Genus="Andrena",
                               SubGenus ="Cnemidandrena",
                               Species="apacheorum",
                               SubSpecies="",
                               Sex="m",
                               Author = "Cockerell",
                               Determiner="J.L. Neff",
                               temp.id= c(36660, 37094, 37239, 37412,
                                          37287, 36999, 37515, 37418,
                                          37166)),

    ## Andrena_costillensis= list(Genus="Andrena",
    ##                            SubGenus ="Cnemidandrena",
    ##                            Species="costillensis",
    ##                            SubSpecies="",
    ##                            Sex="f",
    ##                            Author =
    ##                                "Viereck \\& Cockerell",
    ##                            Determiner="",
    ##                            temp.id= c())

    Andrena_birtwelli_f= list(Genus="Andrena",
                              SubGenus ="",
                              Species="birtwelli",
                              SubSpecies="",
                              Sex="f",
                              Author = "Cockerell",
                              Determiner="J.L. Neff",
                              temp.id= c(37380, 37286, 37227, 37285, 37284,
                                         37283, 37281, 37280, 37279, 37276,
                                         37275, 37274, 37479, 37385, 37482,
                                         37273, 37513, 37483, 37484, 37485,
                                         37486, 37487, 37488, 37489, 37490,
                                         37156, 37155, 37292, 37491, 37492,
                                         37493, 37379, 37494, 37233, 37495,
                                         37496, 37499, 37160, 37500, 37272,
                                         37501, 37502, 37332, 37503, 37497,
                                         37229, 37378, 37231, 37232, 37384,
                                         37383, 37270, 37478, 37477, 37382,
                                         37381, 37228, 37377, 37226, 37225,
                                         37224, 37223, 37222, 37221, 37312,
                                         37298, 37297, 37296, 37269, 37294,
                                         37293, 37291, 37159, 37157, 37158)),

     Andrena_hitei_f= list(Genus="Andrena",
                                 SubGenus ="",
                                 Species="hitei",
                                 SubSpecies="",
                                 Sex="f",
                                 Author = "Cockerell",
                                 Determiner="J.L. Neff",
                                 temp.id= c(36498, 36499)),

     Andrena_segregans_f= list(Genus="Andrena",
                                 SubGenus ="",
                                 Species="segregans",
                                 SubSpecies="",
                                 Sex="f",
                                 Author = "Cockerell",
                                 Determiner="J.L. Neff",
                                 temp.id= c(37066))

)
