
sp.ids <- list(

    ##    Anthidium_maculosum_f = list(Genus="Anthidium",
    ##                                 SubGenus ="Anthidium",
    ##                                 Species="maculosum",
    ##                                 SubSpecies="", Sex="f",
    ##                                 Author = "Cresson",
    ##                                 Determiner = "",
    ##                                 temp.id= c()),

    ##    Anthidium_maculosum_m = list(Genus="Anthidium",
    ##                                 SubGenus ="Anthidium",
    ##                                 Species="maculosum",
    ##                                 SubSpecies="", Sex="m",
    ##                                 Author = "Cresson",
    ##                                 Determiner = "",
    ##                                 temp.id= c()),


    Anthidium_mormonum_m = list(Genus="Anthidium",
                                SubGenus ="",
                                Species="mormonum",
                                SubSpecies="", Sex="m",
                                Author = "Cresson",
                                Determiner = "J.L. Neff",
                                temp.id= c(37249)),

    ## Ashmeadiella_timberlakei_f = list(Genus="Ashmeadiella",
    ##                                  SubGenus ="",
    ##                                  Species="timberlakei",
    ##                                  SubSpecies="", Sex="f",
    ##                                  Author = "Michener",
    ##                                  Determiner = "",
    ##                                  temp.id= c()),

    ##     Ashmeadiella_cactorum_f = list(Genus="Ashmeadiella",
    ##                                  SubGenus ="",
    ##                                  Species="cactorum",
    ##                                  SubSpecies="", Sex="f",
    ##                                  Author = "",
    ##                                  Determiner = "",
    ##                                  temp.id= c()),

    Ashmeadiella_opuntiae_f = list(Genus="Ashmeadiella",
                                   SubGenus ="Ashmeadiella",
                                   Species="opuntiae",
                                   SubSpecies="", Sex="f",
                                   Author = "Cockerell",
                                   Determiner = "J.L. Neff",
                                   temp.id= c(36800, 36951, 36940)),


    Hoplitis_albifrons_f = list(Genus="Hoplitis",
                                SubGenus ="",
                                Species="albifrons",
                                SubSpecies="", Sex="m",
                                Author = "Kirby",
                                Determiner = "J.L. Neff",
                                temp.id= c(36688)),

    Heriades_cruciferae_m = list(Genus="Heriades",
                                 SubGenus ="",
                                 Species="cruciferae",
                                 SubSpecies="", Sex="m",
                                 Author = "Cockerell",
                                 Determiner = "J.L. Neff",
                                 temp.id= c(33583)),

    Coelioxys_moesta_f = list(Genus="Coelioxys",
                              SubGenus ="",
                              Species="moesta",
                              SubSpecies="", Sex="f",
                              Author = "Cresson",
                              Determiner = "J.L. Neff",
                              temp.id= c(37738)),


    Coelioxys_sodalis_f = list(Genus="Coelioxys",
                               SubGenus ="",
                               Species="sodalis",
                               SubSpecies="", Sex="f",
                               Author = "Cresson",
                               Determiner = "J.L. Neff",
                               temp.id= c(36468)),


    ##    Megachile_fidelis_f = list(Genus="Megachile",
    ##                               SubGenus ="Sayapis",
    ##                               Species="fidelis",
    ##                               SubSpecies="",
    ##                               Sex="f",
    ##                               Author = "Cresson",
    ##                               Determiner = "",
    ##                               temp.id= c()),


    ##    Megachile_fidelis_m = list(Genus="Megachile",
    ##                               SubGenus ="Sayapis",
    ##                               Species="fidelis",
    ##                               SubSpecies="",
    ##                               Sex="m",
    ##                               Author = "Cresson",
    ##                               Determiner = "",
    ##                               temp.id= c()),

    Megachile_frigida_f = list(Genus="Megachile",
                               SubGenus ="Xanthosarus",
                               Species="frigida",
                               SubSpecies="",
                               Sex="f", Author = "Smith",
                               Determiner = "J.L. Neff",
                               temp.id=  c(36622, 36848, 37875, 37798,
                                           37908, 37909, 37698, 37958,
                                           37796, 37794, 37795, 37766,
                                           37740, 37605, 37671, 37584,
                                           37675, 37679, 36840, 36644,
                                           36538, 36692, 36763, 36797,
                                           36595, 37680, 33548, 36934,
                                           37721, 37903, 31798, 30764,
                                           31937, 30773)),

    Megachile_frigida_m = list(Genus="Megachile",
                               SubGenus ="Xanthosarus",
                               Species="frigida",
                               SubSpecies="",
                               Sex="m", Author = "Smith",
                               Determiner = "J.L. Neff",
                               temp.id=  c(31358, 31357, 36947,
                                           37669, 37689, 36682,
                                           31933, 31459)),

    ##    Megachile_gemula_f = list(Genus="Megachile",
    ##                           SubGenus ="Xanthosarus",
    ##                               Species="gemula",
    ##                               SubSpecies="fulvogemula",
    ##                              Sex="f", Author = "Cresson",
    ##                               Determiner = "",
    ##                               temp.id=  c()),

    ##    Megachile_subexilis_f = list(Genus="Megachile",
    ##                              SubGenus ="Chelostomoides",
    ##                              Species="subexilis",
    ##                              SubSpecies="",
    ##                              Sex="f", Author = "Cockerell",
    ##                              Determiner = "",
    ##                              temp.id=  c()),


    Megachile_mellitarsis_f = list(Genus="Megachile",
                                   SubGenus ="Sayapis",
                                   Species="mellitarsis",
                                   SubSpecies="", Sex="f",
                                   Author = "Cresson",
                                   Determiner = "J.L. Neff",
                                   temp.id= c(31932, 36994)),

    ##    Heriades_cressoni_f = list(Genus="Heriades",
    ##                               SubGenus ="Neotrypetes",
    ##                               Species="cressoni",
    ##                               SubSpecies="", Sex="f",
    ##                               Author = "Michener",
    ##                               Determiner = "",
    ##                               temp.id= c()),

    Megachile_melanophaea_rohweri_m = list(Genus="Megachile",
                                           SubGenus ="Xanthosarus",
                                           Species="melanophaea",
                                           SubSpecies="rohweri",
                                           Sex="m", Author = "Smith",
                                           Determiner = "J.L. Neff",
                                           temp.id= c(31356, 31465,
                                                      31569, 37105,
                                                      30794, 36796,
                                                      31049, 30906)),


    Megachile_melanophaea_rohweri_f = list(Genus="Megachile",
                                           SubGenus
                                           ="Xanthosarus",
                                           Species="melanophaea",
                                           SubSpecies="rohweri",
                                           Sex="f", Author =
                                                        "Smith", Determiner =
                                                                     "J.L. Neff", temp.id=
                                                                                      c(36946, 30900,
                                                                                        36646, 36681, 38214,
                                                                                        38032, 38205, 36869,
                                                                                        36699, 36549, 30905,
                                                                                        30904, 31048, 30765,
                                                                                        36645, 34264, 30899,
                                                                                        31043, 31934, 30766,
                                                                                        31797, 30902, 36647,
                                                                                        31500, 33225, 36638,
                                                                                        30762, 36889, 36747,
                                                                                        33223, 36608, 36868
                                                                                        )),

    ##    Megachile_zapoteca_m = list(Genus="Megachile",
    ##                                SubGenus ="Xanthosarus",
    ##                                Species="zapoteca",
    ##                                           SubSpecies="",
    ##                                           Sex="m", Author = "Cresson",
    ##                                           Determiner = "",
    ##                                           temp.id= c()),

    ##    Megachile_inimica_m = list(Genus="Megachile",
    ##                               SubGenus ="Sayapis",
    ##                               Species="inimica",
    ##                               SubSpecies="sayi",
    ##                               Sex="m", Author = "Cresson",
    ##                               Determiner = "",
    ##                               temp.id=  c()),


    ##    Megachile_mellitarsis_f = list(Genus="Megachile",
    ##                                   SubGenus ="Sayapis",
    ##                                   Species="mellitarsis",
    ##                                   SubSpecies="", Sex="f",
    ##                                   Author = "Cresson",
    ##                                   Determiner = "",
    ##                                   temp.id= c()),

    Megachile_mellitarsis_m = list(Genus="Megachile",
                                   SubGenus ="Sayapis",
                                   Species="mellitarsis",
                                   SubSpecies="", Sex="m",
                                   Author = "Cresson",
                                   Determiner = "J.L. Neff",
                                   temp.id= c(32770, 34105, 32771)),

    Megachile_comata_f = list(Genus="Megachile",
                              SubGenus ="Xanthosarus",
                              Species="comata",
                              SubSpecies="",
                              Sex="f",
                              Author = "Cresson",
                              Determiner = "J.L. Neff",
                              temp.id= c(33141, 33934)),

    Megachile_comata_m = list(Genus="Megachile",
                              SubGenus ="Xanthosarus",
                              Species="comata", SubSpecies="",
                              Sex="m",
                              Author = "Cresson",
                              Determiner = "J.L. Neff",
                              temp.id= c(33222, 30793, 33932,
                                         36451, 31935, 30901,
                                         31936)),

    ##    Megachile_relativa_f = list(Genus="Megachile",
    ##                                SubGenus ="Megachile",
    ##                                Species="relativa",
    ##                                SubSpecies="", Sex="f",
    ##                                Author = "Cresson",
    ##                                Determiner = "",
    ##                                temp.id= c())

    Megachile_perihirta_f = list(Genus="Megachile",
                                 SubGenus ="Xanthosarus",
                                 Species="",
                                 SubSpecies="", Sex="f",
                                 Author = "Cockerell",
                                 Determiner = "J.L. Neff",
                                 temp.id= c(36527)),

    Megachile_lippiae_f = list(Genus="Megachile",
                               SubGenus ="Litomegachile",
                               Species="",
                               SubSpecies="", Sex="f",
                               Author = "Cockerell",
                               Determiner = "J.L. Neff",
                               temp.id= c(33056)),

    Megachile_onobrychidis_m = list(Genus="Megachile",
                                    SubGenus ="Litomegachile",
                                    Species="",
                                    SubSpecies="", Sex="m",
                                    Author = "Cockerell",
                                    Determiner = "J.L. Neff",
                                    temp.id= c(36705, 30779)),

    Osmia_coloradensis_f = list(Genus="Osmia",
                                SubGenus ="Helicosmia",
                                Species="coloradensis",
                                SubSpecies="", Sex="f",
                                Author = "Cresson",
                                Determiner = "J.L. Neff",
                                temp.id= c(31040, 30647, 30650)),

    Osmia_gaudiosa_f = list(Genus="Osmia",
                            SubGenus ="Melanosmia",
                            Species="gaudiosa",
                            SubSpecies="", Sex="f",
                            Author = "Cockerell",
                            Determiner = "J.L. Neff",
                            temp.id= c(30921)),

    Osmia_penstemonis_f = list(Genus="Osmia", SubGenus
                               ="Melanosmia",
                               Species="penstemonis",
                               SubSpecies="", Sex="f", Author =
                                                           "Cockerell", Determiner =
                                                                            "J.L. Neff", temp.id= c(36823,
                                                                                                    30924, 30929, 30770, 36683,
                                                                                                    30933, 36651, 30940)),

    Osmia_subaustralis_f = list(Genus="Osmia",
                                SubGenus ="Cephalosmia",
                                Species="subaustralis",
                                SubSpecies="", Sex="f",
                                Author = "Cockerell",
                                Determiner = "J.L. Neff",
                                temp.id= c(31501, 31566)),

    Osmia_sp_a_f = list(Genus="Osmia",
                        SubGenus ="",
                        Species="sp.",
                        SubSpecies="a", Sex="f",
                        Author = "",
                        Determiner = "J.L. Neff",
                        temp.id= c(36789, 36584, 32272))



)
