
sp.ids <- list(

    Anthidium_maculosum_f = list(Genus="Anthidium",
                                 SubGenus ="Anthidium",
                                 Species="maculosum",
                                 SubSpecies="", Sex="f",
                                 Author = "Cresson",
                                 Determiner = "",
                                 temp.id= c()),

    Anthidium_maculosum_m = list(Genus="Anthidium",
                                 SubGenus ="Anthidium",
                                 Species="maculosum",
                                 SubSpecies="", Sex="m",
                                 Author = "Cresson",
                                 Determiner = "",
                                 temp.id= c()),

    Megachile_fidelis_f = list(Genus="Megachile",
                               SubGenus ="Sayapis",
                               Species="fidelis",
                               SubSpecies="",
                               Sex="f",
                               Author = "Cresson",
                               Determiner = "",
                               temp.id= c()),

    Megachile_fidelis_m = list(Genus="Megachile",
                               SubGenus ="Sayapis",
                               Species="fidelis",
                               SubSpecies="",
                               Sex="m",
                               Author = "Cresson",
                               Determiner = "",
                               temp.id= c()),

    Megachile_frigida_f = list(Genus="Megachile",
                               SubGenus ="Xanthosarus",
                               Species="frigida",
                               SubSpecies="",
                               Sex="f", Author = "Smith",
                               Determiner = "",
                               temp.id=  c()),

    Megachile_frigida_m = list(Genus="Megachile",
                               SubGenus ="Xanthosarus",
                               Species="frigida",
                               SubSpecies="",
                               Sex="m", Author = "Smith",
                               Determiner = "",
                               temp.id=  c(
                                           )),

    Megachile_gemula_f = list(Genus="Megachile",
                           SubGenus ="Xanthosarus",
                               Species="gemula",
                               SubSpecies="fulvogemula",
                              Sex="f", Author = "Cresson",
                               Determiner = "",
                               temp.id=  c()),

    Megachile_subexilis_f = list(Genus="Megachile",
                              SubGenus ="Chelostomoides",
                              Species="subexilis",
                              SubSpecies="",
                              Sex="f", Author = "Cockerell",
                              Determiner = "",
                              temp.id=  c()),


    Megachile_mellitarsis_f = list(Genus="Megachile",
                                   SubGenus ="Sayapis",
                                   Species="mellitarsis",
                                   SubSpecies="", Sex="f",
                                   Author = "Cresson",
                                   Determiner = "",
                                   temp.id= c()),

    Heriades_cressoni_f = list(Genus="Heriades",
                               SubGenus ="Neotrypetes",
                               Species="cressoni",
                               SubSpecies="", Sex="f",
                               Author = "Michener",
                               Determiner = "",
                               temp.id= c()),

    Megachile_melanophaea_rohweri_m = list(Genus="Megachile",
                                           SubGenus ="Xanthosarus",
                                           Species="melanophaea",
                                           SubSpecies="rohweri",
                                           Sex="m", Author = "Smith",
                                           Determiner = "",
                                           temp.id= c()),


    Megachile_melanophaea_rohweri_f = list(Genus="Megachile",
                                           SubGenus ="Xanthosarus",
                                           Species="melanophaea",
                                           SubSpecies="rohweri",
                                           Sex="f", Author = "Smith",
                                           Determiner = "",
                                           temp.id= c(
                                                      )),

    Megachile_zapoteca_m = list(Genus="Megachile",
                                SubGenus ="Xanthosarus",
                                Species="zapoteca",
                                           SubSpecies="",
                                           Sex="m", Author = "Cresson",
                                           Determiner = "",
                                           temp.id= c()),

    Megachile_inimica_m = list(Genus="Megachile",
                               SubGenus ="Sayapis",
                               Species="inimica",
                               SubSpecies="sayi",
                               Sex="m", Author = "Cresson",
                               Determiner = "",
                               temp.id=  c()),


    Megachile_mellitarsis_f = list(Genus="Megachile",
                                   SubGenus ="Sayapis",
                                   Species="mellitarsis",
                                   SubSpecies="", Sex="f",
                                   Author = "Cresson",
                                   Determiner = "",
                                   temp.id= c()),

    Megachile_mellitarsis_m = list(Genus="Megachile",
                                   SubGenus ="Sayapis",
                                   Species="mellitarsis",
                                   SubSpecies="", Sex="m",
                                   Author = "Cresson",
                                   Determiner = "",
                                   temp.id= c()),

    Megachile_comata_f = list(Genus="Megachile",
                              SubGenus ="Xanthosarus",
                              Species="comata",
                              SubSpecies="",
                              Sex="f",
                              Author = "Cresson", Determiner = "",
                              temp.id= c()),

    Megachile_comata_m = list(Genus="Megachile",
                              SubGenus ="Xanthosarus",
                              Species="comata", SubSpecies="",
                              Sex="m",
                              Author = "Cresson",
                              Determiner = "",
                              temp.id= c()),

    Megachile_relativa_f = list(Genus="Megachile",
                                SubGenus ="Megachile",
                                Species="relativa",
                                SubSpecies="", Sex="f",
                                Author = "Cresson",
                                Determiner = "",
                                temp.id= c())


)
