
sp.ids <- list(

       Calliopsis_chlorops = list(Genus="Calliopsis",
                                      SubGenus ="",
                                      Species="chlorops",
                                      SubSpecies="",
                                      Sex="m", Author = "Cockerell",
                                      Determiner="J.L. Neff",
                                      temp.id= c("18964")),
      
      
      Pseudopanurgus_piercei_f= list(Genus="Pseudopanurgus",
                                      SubGenus ="",
                                      Species="piercei",
                                      SubSpecies="",
                                      Sex="f", Author = "Crawford",
                                      Determiner="D. Yanega",
                                      temp.id= c("17946")),


    Pseudopanurgus_atricornis_f= list(Genus="Pseudopanurgus",
                                      SubGenus ="",
                                      Species="atricornis",
                                      SubSpecies="",
                                      Sex="f", Author = "Cresson",
                                      Determiner="D. Yanega",
                                      temp.id= c("18719", "17996",
                                                 "17863", "17805",
                                                 "18026", "18054",
                                                 "18158", "18017",
                                                 "18166", "18147",
                                                 "18106", "18257",
                                                 "18333", "17810",
                                                 "18492", "18583",
                                                 "17934", "18142",
                                                 "18134", "18120",
                                                 "18088", "18139",
                                                 "17966", "17968",
                                                 "18091", "18352",
                                                 "18145", "18146",
                                                 "17867", "18137",
                                                 "18138", "18122",
                                                 "18136", "18673",
                                                 "18301", "17868",
                                                 "18665", "18608",
                                                 "17875", "17862",
                                                 "18088","17953",
                                                 "18167","19793",
                                                 "19747")),


    Pseudopanurgus_atricornis_m= list(Genus="Pseudopanurgus",
                                      SubGenus ="",
                                      Species="atricornis",
                                      SubSpecies="",
                                      Sex="m", Author = "Cresson",
                                      Determiner="D. Yanega",
                                      temp.id= c("18507", "18478",
                                                 "18437", "18289",
                                                 "18510", "18452",
                                                 "18144", "18135",
                                                 "18078", "17964",
                                                 "18129", "18474",
                                                 "18332", "17952",
                                                 "18286", "18575",
                                                 "18468", "18423",
                                                 "17965", "18482",
                                                 "17866", "18424",
                                                 "17864", "17869",
                                                 "18060", "18354",
                                                 "18329", "18079",
                                                 "18663", "17871",
                                                 "18067", "18330",
                                                 "17860", "18456",
                                                 "18130", "18170",
                                                 "17883", "18058",
                                                 "18068", "17967",
                                                 "18149", "18133",
                                                 "18331", "18141",
                                                 "18105", "18508",
                                                 "17874", "18450",
                                                 "18457", "18496",
                                                 "18529", "18081",
                                                 "17951", "18123",
                                                 "18522", "18461",
                                                 "18428")),

      Panurginus_cressoniellus_f= list(Genus="Panurginus", SubGenus ="",
                                     Species="cressoniellus",
                                     SubSpecies="",
                                     Sex="f", Author = "Cockerell",
                                     Determiner="D. Yanega","J.L. Neff",
                                     temp.id= c("18695","19674")),


    Protandrena_sp_a= list(Genus="Protandrena", SubGenus ="",
                           Species="sp.",
                           SubSpecies="a",
                           Sex="f", Author = "",
                           Determiner="D. Yanega",
                           temp.id= c("18574")),


    Protandrena_sp_c= list(Genus="Protandrena", SubGenus ="",
                           Species="sp.",
                           SubSpecies="c",
                           Sex="m", Author = "",
                           Determiner="D. Yanega",
                           temp.id= c("18469")),

        Protandrena_sp_d= list(Genus="Protandrena", SubGenus ="",
                           Species="sp.",
                           SubSpecies="d",
                           Sex="f", Author = "",
                           Determiner="D. Yanega",
                           temp.id= c("18678")),

      Protandrena_sp_d= list(Genus="Protandrena", SubGenus ="",
                           Species="sp.",
                           SubSpecies="d",
                           Sex="m", Author = "",
                           Determiner="D. Yanega",
                           temp.id= c("18317")),

      Protandrena_sp_d= list(Genus="Protandrena", SubGenus ="",
                           Species="sp.",
                           SubSpecies="e",
                           Sex="m", Author = "",
                           Determiner="D. Yanega",
                           temp.id= c("18411")),



    Pseudopanurgus_porterae_f= list(Genus="Pseudopanurgus",
                                SubGenus ="",
                                Species="porterae",
                                SubSpecies="",
                                Sex="f",
                                Author = "Cockerell",
                                Determiner="D. Yanega",
                                temp.id= c("18738", "17775", "17776",
                                "17781", "17789", "17780", "18733",
                                "18728", "18616", "17793", "17790",
                                "17791")),



    Pseudopanurgus_porterae_m= list(Genus="Pseudopanurgus",
                                SubGenus ="",
                                Species="porterae",
                                SubSpecies="",
                                Sex="m",
                                Author = "Cockerell",
                                Determiner="D. Yanega",
                                temp.id= c("18615", "18732", "17783",
                                           "18729", "17792")),


    Andrena_argemonis_f = list(Genus="Andrena",
                               SubGenus="Plastandrena",
                               Species="argemonis",
                               SubSpecies="",
                               Sex="f", Author = "Cockerell",
                               Determiner="L. Ponisio",
                               temp.id= c("18021", "18171")),

    Andrena_argemonis_m = list(Genus="Andrena",
                               SubGenus="Plastandrena",
                               Species="argemonis",
                               SubSpecies="",
                               Sex="m", Author = "Cockerell",
                               Determiner="L. Ponisio",
                               temp.id= c("18269")),


    Heterosarus_bakeri_f= list(Genus="Heterosarus",
                               SubGenus ="",
                               Species="bakeri",
                               SubSpecies="",
                               Sex="f",
                               Author = "Cockerell",
                               Determiner="D. Yanega","J.L. Neff",
                               temp.id= c("18198", "18288", "18041",
                                          "18238", "18069", "17808",
                                          "17648", "17976", "18184",
                                          "17809", "17814", "18117",
                                          "18210", "17691", "18541",
                                          "18193", "18433", "17800",
                                          "17832", "18686", "18200",
                                          "18016", "17654", "18270",
                                          "19925", "25084", "19667",
                                          "19416", "20148")),


    Heterosarus_bakeri_m= list(Genus="Heterosarus",
                               SubGenus ="",
                               Species="bakeri",
                               SubSpecies="",
                               Sex="m",
                               Author = "Cockerell",
                               Determiner="D. Yanega",
                               temp.id= c(
                                   "18002", "18197", "18209")),


    Heterosarus_neomex_f= list(Genus="Heterosarus",
                               SubGenus ="",
                               Species="neomexicanus",
                               SubSpecies="",
                               Sex="f",
                               Author = "Cockerell",
                               Determiner="D. Yanega",
                               temp.id= c( "18744",  "17994", "17870",
                                          "18769", "18196",
                                          "18557", "17861",
                                          "18172", "17876", "18015",
                                          "17997", "18743", "18410",
                                          "17897",  "18481", "18369",
                                          "18397")),

    Panurginus_sp_a_f= list(Genus="Panurginus", SubGenus ="",
                            Species="sp.",
                            SubSpecies="a",
                            Sex="f", Author = "",
                            Determiner="D. Yanega",
                            temp.id= c("18711")),

    Panurginus_cressoniellus_f= list(Genus="Panurginus", SubGenus ="",
                                     Species="cressoniellus",
                                     SubSpecies="",
                                     Sex="f", Author = "Cockerell",
                                     Determiner="D. Yanega",
                                     temp.id= c("18579")),

    
    Andrena_apacheorum_f= list(Genus="Andrena", SubGenus ="Cnemidandrena",
                               Species="apacheorum",
                               SubSpecies="",
                               Sex="f",
                               Author = "Cockerell",
                               Determiner="D. Yanega", temp.id=
                                                           c("17796",
                                                             "17798",
                                                             "17710",
                                                             "17819",
                                                             "17744",
                                                             "17859",
                                                             "18183",
                                                             "18220",
                                                             "18000",
                                                             "18296",
                                                             "18057",
                                                             "17834",
                                                             "17738",
                                                             "17857",
                                                             "17855",
                                                             "18489",
                                                             "17998",
                                                             "18195",
                                                             "18191",
                                                             "17999",
                                                             "18013",
                                                             "17650",
                                                             "17884",
                                                             "17877",
                                                             "18463",
                                                             "18480",
                                                             "17889",
                                                             "17888",
                                                             "17887",
                                                             "17886",
                                                             "17885",
                                                             "17882",
                                                             "18328",
                                                             "18326",
                                                             "18477")),

    Andrena_apacheorum_m= list(Genus="Andrena", SubGenus ="Cnemidandrena",
                               Species="apacheorum",
                               SubSpecies="",
                               Sex="m",
                               Author = "Cockerell",
                               Determiner="D. Yanega", temp.id=
                                                           c( "18551",
                                                             "18549",
                                                             "17978")),

    Andrena_costillensis= list(Genus="Andrena", SubGenus ="Cnemidandrena",
                               Species="costillensis", SubSpecies="",
                               Sex="f",
                               Author =
                                   "Viereck \\& Cockerell",
                               Determiner="D. Yanega",
                               temp.id= c("18720"))




)
