
sp.ids <- list(

    Pseudopanurgus_atricornis_f= list(Genus="Pseudopanurgus",
                                      SubGenus ="",
                                      Species="atricornis",
                                      SubSpecies="",
                                      Sex="f", Author = "Cresson",
                                      Determiner="D. Yanega",
                                      temp.id= c("18719", "17996",
                                                 "17863", "17805",
                                                 "18026", "18054",
                                                 "18158", "18017",
                                                 "18166", "18147",
                                                 "18106", "18257",
                                                 "18333", "17810",
                                                 "18492", "18583",
                                                 "17934", "18142",
                                                 "18134", "18120",
                                                 "18088", "18139",
                                                 "17966", "17968",
                                                 "18091", "18352",
                                                 "18145", "18146",
                                                 "17867", "18137",
                                                 "18138", "18122",
                                                 "18136", "18673",
                                                 "18301", "17868",
                                                 "18665", "18608",
                                                 "17875", "17862")),


    Pseudopanurgus_atricornis_m= list(Genus="Pseudopanurgus",
                                      SubGenus ="",
                                      Species="atricornis",
                                      SubSpecies="",
                                      Sex="m", Author = "Cresson",
                                      Determiner="D. Yanega",
                                      temp.id= c("18507", "18478",
                                                 "18437", "18289",
                                                 "18510", "18452",
                                                 "18144", "18135",
                                                 "18078", "17964",
                                                 "18129", "18474",
                                                 "18332", "17952",
                                                 "18286", "18575",
                                                 "18468", "18423",
                                                 "17965", "18482",
                                                 "17866", "18424",
                                                 "17864", "17869",
                                                 "18060", "18354",
                                                 "18329", "18079",
                                                 "18663", "17871",
                                                 "18067", "18330",
                                                 "17860", "18456",
                                                 "18130", "18170",
                                                 "17883", "18058",
                                                 "18068", "17967",
                                                 "18149", "18133",
                                                 "18331", "18141",
                                                 "18105", "18508",
                                                 "17874", "18450",
                                                 "18457", "18496",
                                                 "18529", "18081",
                                                 "17951", "18123",
                                                 "18522", "18461",
                                                 "18428")),


    Pseudopanurgus_sp_a_f= list(Genus="Pseudopanurgus",
                                SubGenus ="",
                                Species="sp.",
                                SubSpecies="a",
                                Sex="f",
                                Author = "",
                                Determiner="D. Yanega",
                                temp.id= c("18458", "18433", "17800",
                                           "17832")),

    Pseudopanurgus_sp_a_m= list(Genus="Pseudopanurgus",
                                SubGenus ="",
                                Species="sp.",
                                SubSpecies="a",
                                Sex="m",
                                Author = "",
                                Determiner="D. Yanega",
                                temp.id= c("18002", "1897", "18209")),

    Pseudopanurgus_sp_b_f= list(Genus="Pseudopanurgus",
                                SubGenus ="",
                                Species="sp.",
                                SubSpecies="b",
                                Sex="f",
                                Author = "",
                                Determiner="D. Yanega",
                                temp.id= c("17780", "17789", "17781",
                                           "17776", "17775", "18738",
                                           "17791", "17790", "17793",
                                           "18616", "18728", "18733")),

    Pseudopanurgus_sp_b_m= list(Genus="Pseudopanurgus",
                                SubGenus ="",
                                Species="sp.",
                                SubSpecies="b",
                                Sex="m",
                                Author = "",
                                Determiner="D. Yanega",
                                temp.id= c("18615", "18732", "17783",
                                           "18729", "17792")),


    Pseudopanurgus_sp_c_f= list(Genus="Pseudopanurgus",
                                SubGenus ="",
                                Species="sp.",
                                SubSpecies="c",
                                Sex="f",
                                Author = "",
                                Determiner="D. Yanega",
                                temp.id= c("18353", "18679", "18574",
                                           "18340")),

    Pseudopanurgus_sp_d_f= list(Genus="Pseudopanurgus",
                                SubGenus ="",
                                Species="sp.",
                                SubSpecies="c",
                                Sex="f",
                                Author = "",
                                Determiner="D. Yanega",
                                temp.id= c("18167")),

    Pseudopanurgus_sp_e_f= list(Genus="Pseudopanurgus",
                                SubGenus ="",
                                Species="sp.",
                                SubSpecies="c",
                                Sex="f",
                                Author = "",
                                Determiner="D. Yanega",
                                temp.id= c("18678")),


    Diadasia_diminuta_f = list(Genus="Diadasia",
                               SubGenus="Coquillettapis",
                               Species="diminuta",
                               SubSpecies="", Sex="f",
                               Author = "Cresson",
                               Determiner="L.C. Ponisio",
                               temp.id= c("18080", "17839")),

    Anthophora_montana_f = list(Genus="Anthophora",
                                SubGenus="Mystacanthophora",
                                Species="montana",
                                SubSpecies="",
                                Sex="f",
                                Author = "Cresson",
                                Determiner="L.C. Ponisio",
                                temp.id= c("18599", "18237", "18101",
                                           "18102")),

    Anthophora_montana_m = list(Genus="Anthophora",
                                SubGenus="Mystacanthophora",
                                Species="montana", SubSpecies="",
                                Sex="m", Author = "Cresson",
                                Determiner="L.C. Ponisio",
                                temp.id= c("18607")),

    Apis_mellifera_f = list(Genus="Apis", SubGenus = "Apis",
                            Species="mellifera",
                            SubSpecies="", Sex="f",
                            Author = "Linnaeus",
                            Determiner="L.C. Ponisio",
                            temp.id= c("18010", "18202", "18024",
                                       "18023", "20410", "20411",
                                       "20413","20414", "20415",
                                       "20416","20418","20419",
                                       "20420","20421")),

    Nomada_spc= list(Genus="Nomada", SubGenus="",
                     Species="sp. c",
                     SubSpecies="", Sex="f",
                     Author = "",
                     Determiner="L.C. Ponisio",
                     temp.id= c("17895", "18382")),

    Andrena_argemonis_f = list(Genus="Andrena",
                               SubGenus="Plastandrena",
                               Species="argemonis",
                               SubSpecies="",
                               Sex="f", Author = "Cockerell",
                               Determiner="L. Ponisio",
                               temp.id= c("18021", "18171")),

    Andrena_argemonis_m = list(Genus="Andrena",
                               SubGenus="Plastandrena",
                               Species="argemonis",
                               SubSpecies="",
                               Sex="m", Author = "Cockerell",
                               Determiner="L. Ponisio",
                               temp.id= c("18269")),


    Bombus_centralis_f = list(Genus = "Bombus",
                              SubGenus="Pyrobombus",
                              Species = "centralis",
                              SubSpecies = "", Sex ="f",
                              Author = "Cresson",
                              Determiner="K. Watrous",
                              temp.id = c("18561", "18558")),

    Bombus_rufocinctus_f = list(Genus = "Bombus",
                                SubGenus="Cullumanobombus",
                                Species ="rufocinctus",
                                SubSpecies = "", Sex ="f",
                                Author = "Cresson",
                                Determiner="K. Watrous",
                                temp.id = c("18559")),


    Bombus_huntii_f = list(Genus = "Bombus",
                           SubGenus="Pyrobombus",
                           Species = "huntii",
                           SubSpecies = "", Sex ="f", Author = "Greene",
                           Determiner="K. Watrous",
                           temp.id = c("17931")),


    Heterosarus_sp_a_f= list(Genus="Heterosarus",
                             SubGenus ="",
                             Species="sp.",
                             SubSpecies="a",
                             Sex="f",
                             Author = "",
                             Determiner="D. Yanega",
                             temp.id= c("18198", "18015", "18288",
                                        "18041", "17897", "17654",
                                        "18200", "18686", "18238",
                                        "17861", "18743", "18410",
                                        "18069", "18270", "17876",
                                        "18196", "18557", "18172",
                                        "17808", "18481", "17648",
                                        "18016", "17870", "17976",
                                        "18184", "17809", "17814",
                                        "18117", "18210", "18769",
                                        "17691", "17997", "17994",
                                        "18541", "18193", "18744")),

    Panurginus_sp_a_f= list(Genus="Panurginus", SubGenus ="",
                            Species="sp.",
                            SubSpecies="a",
                            Sex="f", Author = "",
                            Determiner="D. Yanega",
                            temp.id= c("18711")),

    Panurginus_cressoniellus_f= list(Genus="Panurginus", SubGenus ="",
                                     Species="cressoniellus",
                                     SubSpecies="",
                                     Sex="f", Author = "Cockerell",
                                     Determiner="D. Yanega",
                                     temp.id= c("18579")),

    Triepeolus_sp_a_f= list(Genus="Triepeolus",
                            SubGenus="",
                            Species="sp.",
                            SubSpecies="a",
                            Sex="f",
                            Author = "",
                            Determiner="D. Yanega",
                            temp.id= c("18384",
                                       "18321",
                                       "17731",
                                       "18386",
                                       "18425",
                                       "18403",
                                       "18416"
                                       )),



    Triepeolus_sp_a_m= list(Genus="Triepeolus",
                            SubGenus="",
                            Species="sp.",
                            SubSpecies="a",
                            Sex="m",
                            Author = "",
                            Determiner="D. Yanega",
                            temp.id= c("18401",
                                       "17893",
                                       "18363",
                                       "18745",
                                       "18343",
                                       "18757",
                                       "18402",
                                       "17915",
                                       "17908",
                                       "18421",
                                       "18357",
                                       "18389",
                                       "17901" )),

    Triepeolus_sp_b_f= list(Genus="Triepeolus",
                            SubGenus="",
                            Species="sp.",
                            SubSpecies="b",
                            Sex="f",
                            Author = "",
                            Determiner="D. Yanega",
                            temp.id= c("18059",
                                       "18092")),

    Andrena_apacheorum_f= list(Genus="Andrena", SubGenus ="Cnemidandrena",
                               Species="apacheorum",
                               SubSpecies="",
                               Sex="f",
                               Author = "Cockerell",
                               Determiner="D. Yanega", temp.id=
                                                           c("17796",
                                                             "17798",
                                                             "17710",
                                                             "17819",
                                                             "17744",
                                                             "17859",
                                                             "18183",
                                                             "18220",
                                                             "18000",
                                                             "18296",
                                                             "18057",
                                                             "17834",
                                                             "17738",
                                                             "17857",
                                                             "17855",
                                                             "18489",
                                                             "17998",
                                                             "18195",
                                                             "18191",
                                                             "17999",
                                                             "18013",
                                                             "17650",
                                                             "17884",
                                                             "17877",
                                                             "18463",
                                                             "18480",
                                                             "17889",
                                                             "17888",
                                                             "17887",
                                                             "17886",
                                                             "17885",
                                                             "17882",
                                                             "18328",
                                                             "18326",
                                                             "18477")),

    Andrena_apacheorum_m= list(Genus="Andrena", SubGenus ="Cnemidandrena",
                               Species="apacheorum",
                               SubSpecies="",
                               Sex="m",
                               Author = "Cockerell",
                               Determiner="D. Yanega", temp.id=
                                                           c( "18551",
                                                             "18549",
                                                             "17978")),

       Andrena_costillensis= list(Genus="Andrena", SubGenus ="Cnemidandrena",
                               Species="costillensis", SubSpecies="",
                               Sex="f",
                               Author =
                                   "Viereck \\& Cockerell",
                               Determiner="RW Thorp",
                               temp.id= c("18720"))




)
