
sp.ids <- list(

    Agapostemen_angelicus_f = list(Genus="Agapostemon",
                                   SubGenus ="Agapostemon",
                                   Species="angelicus", SubSpecies="",
                                   Sex="f", Author = "Cockerell",
                                   Determiner = "L.C. Ponisio",
                                   temp.id=
                                       c("18697","17928","17835",
                                         "17828","17820", "17841",
                                         "18151", "18163", "18164",
                                         "18165", "18148", "17974",
                                         "17926", "17930", "18085")),

    Agapostemen_angelicus_m = list(Genus="Agapostemon",
                                   SubGenus ="Agapostemon",
                                   Species="angelicus",
                                   SubSpecies="",
                                   Sex="m", Author = "Cockerell",
                                   Determiner = "L.C. Ponisio",
                                   temp.id= c("17959", "18125",
                                              "18128", "17963",
                                              "17950", "17941",
                                              "17797", "18243",
                                              "17713")),

    Sphecodes_morphoa_f= list(Genus="Sphecodes", SubGenus ="",
                              Species="sp.",
                              SubSpecies="a", Sex="f",
                              Author = "",
                              Determiner ="",
                              temp.id= c("18664", "18335")),

    Sphecodes_morphob_f= list(Genus="Sphecodes", SubGenus ="",
                              Species="sp.",
                              SubSpecies="b", Sex="f",
                              Author = "",
                              Determiner ="",
                              temp.id= c("18121", "18131", "18160",
                                         "18212", "18216", "17939",
                                         "17970", "17969", "17972")),


    Dufourea_maura_f= list(Genus="Dufourea", SubGenus ="",
                           Species="maura", SubSpecies="",
                           Sex="f", Author = "Cresson",
                           Determiner = "L.C. Ponisio",
                           temp.id= c("17665", "18432", "18427",
                                      "17936", "17935", "17940",
                                      "18306")),

    Dufourea_maura_m= list(Genus="Dufourea", SubGenus ="",
                           Species="maura", SubSpecies="",
                           Sex="m", Author = "Cresson",
                           Determiner = "L.C. Ponisio",
                           temp.id= c("18124", "18242")),


    Halictus_ligatus_f= list(Genus="Halictus", SubGenus ="Odontalictus",
                             Species="ligatus", SubSpecies="",
                             Sex="f", Author = "Say",
                             Determiner = "D. Yanega",
                             temp.id= c("17853", "18737")),

      Halictus_tripartitus_f= list(Genus="Halictus",
                                 SubGenus ="Seladonia",
                                 Species="tripartitus",
                                 SubSpecies="", Sex="f",
                                Author = "Cockerell",
                                Determiner = "D. Yanega",
                                temp.id= c("18104")),

    Lasioglossum_sisymbrii_m = list(Genus="Lasioglossum", SubGenus
                                    ="Lasioglossum",
                                    Species="sisymbrii",
                                    SubSpecies="",
                                    Sex="m",
                                    Author = "Cockerell",
                                    Determiner = "D. Yanega",
                                    temp.id=
                                        c("18580",
                                          "18581",
                                          "18593"
                                          "17977")),

        Lasioglossum_aquilae_f = list(Genus="Lasioglossum",
                                  SubGenus ="Dialictus",
                                  Species="aquilae",
                                SubSpecies="",
                                Sex="f", Author = "Cockerell",
                                Determiner = "D. Yanega",
                                temp.id= c(
                                    "18050",
                                    "17811",
                                    "18676",
                                    "18677",
                                    "18297",
                                    "18316",
                                    "18076",
                                    "18523",
                                    "18275",
                                    "18112",
                                    "17816",
                                    "18690",
                                    "18494",
                                    "18687",
                                    "18712",
                                    "18503",
                                    "18056",
                                    "18716",
                                    "18065",
                                    "18709",
                                    "18089",
                                    "18107",
                                    "18086",
                                    "18702",
                                    "18048",
                                    "18310",
                                    "18294",
                                    "18292",
                                    "18278",
                                    "18350",
                                    "18053",
                                    "18055",
                                    "18703"))



)
