
sp.ids <- list(
    Agapostemen_angelicus_f = list(Genus="Agapostemon",
                                   SubGenus ="Agapostemon",
                                   Species="angelicus", SubSpecies="",
                                   Sex="f", Author = "Cockerell",
                                   Determiner = "L.C. Ponisio",
                                   temp.id=
                                       c("18697","17928","17835",
                                         "17828","17820", "17841",
                                         "18151", "18163", "18164",
                                         "18165", "18148", "17974",
                                         "17926", "17930", "18085")),

    Agapostemen_angelicus_m = list(Genus="Agapostemon",
                                   SubGenus ="Agapostemon",
                                   Species="angelicus",
                                   SubSpecies="",
                                   Sex="m", Author = "Cockerell",
                                   Determiner = "L.C. Ponisio",
                                   temp.id= c("17959", "18125",
                                              "18128", "17963",
                                              "17950", "17941",
                                              "17797", "18243",
                                              "17713")),

    Sphecodes_morphoa_f= list(Genus="Sphecodes", SubGenus ="",
                              Species="sp.",
                              SubSpecies="a", Sex="f",
                              Author = "",
                              Determiner ="",
                              temp.id= c("18664", "18335")),

    Sphecodes_morphob_f= list(Genus="Sphecodes", SubGenus ="",
                              Species="sp.",
                              SubSpecies="b", Sex="f",
                              Author = "",
                              Determiner ="",
                              temp.id= c("18121", "18131", "18160",
                                         "18212", "18216", "17939",
                                         "17970", "17969", "17972")),


    Dufourea_maura_f= list(Genus="Dufourea", SubGenus ="",
                           Species="maura", SubSpecies="",
                           Sex="f", Author = "Cresson",
                           Determiner = "L.C. Ponisio",
                           temp.id= c("17665", "18432", "18427",
                                      "17936", "17935", "17940",
                                      "18306")),

    Dufourea_maura_m= list(Genus="Dufourea", SubGenus ="",
                           Species="maura", SubSpecies="",
                           Sex="m", Author = "Cresson",
                           Determiner = "L.C. Ponisio",
                           temp.id= c("18124", "18242")),


    Halictus_ligatus_f= list(Genus="Halictus", SubGenus ="Odontalictus",
                             Species="ligatus", SubSpecies="",
                             Sex="f", Author = "Say",
                             Determiner = "D. Yanega",
                             temp.id= c("17853", "18737",
                                        "18143", "17975")),


    Halictus_tripartitus_f= list(Genus="Halictus",
                                 SubGenus ="Seladonia",
                                 Species="tripartitus",
                                 SubSpecies="", Sex="f",
                                 Author = "Cockerell",
                                 Determiner = "D. Yanega",
                                 temp.id= c("18104",
                                            "18307")),

    Lasioglossum_sisymbrii_m = list(Genus="Lasioglossum",
                                    SubGenus ="Lasioglossum",
                                    Species="sisymbrii",
                                    SubSpecies="",
                                    Sex="m",
                                    Author = "Cockerell",
                                    Determiner = "D. Yanega",
                                    temp.id=
                                        c("18580",
                                          "18581",
                                          "18593",
                                          "17977")),

    Lasioglossum_aquilae_f = list(Genus="Lasioglossum",
                                  SubGenus ="Dialictus",
                                  Species="aquilae",
                                  SubSpecies="",
                                  Sex="f", Author = "Cockerell",
                                  Determiner = "D. Yanega",
                                  temp.id= c(
                                      "18050",
                                      "17811",
                                      "18676",
                                      "18677",
                                      "18297",
                                      "18316",
                                      "18076",
                                      "18523",
                                      "18275",
                                      "18112",
                                      "17816",
                                      "18690",
                                      "18494",
                                      "18687",
                                      "18712",
                                      "18503",
                                      "18056",
                                      "18716",
                                      "18065",
                                      "18709",
                                      "18089",
                                      "18107",
                                      "18086",
                                      "18702",
                                      "18048",
                                      "18310",
                                      "18294",
                                      "18292",
                                      "18278",
                                      "18350",
                                      "18053",
                                      "18055",
                                      "18703")),


    Lasioglossum_aquilae_f = list(Genus="Lasioglossum",
                                  SubGenus ="Dialictus",
                                  Species="aquilae",
                                  SubSpecies="",
                                  Sex="m", Author = "Cockerell",
                                  Determiner = "J. Gardener",
                                  temp.id= c("18064", "18704")),

    Lasioglossum_M2_f = list(Genus="Lasioglossum",
                             SubGenus ="Dialictus",
                             Species="M2",
                             SubSpecies="",
                             Sex="f", Author = "",
                             Determiner = "J. Gardener",
                             temp.id= c("17726", "18459", "17739")),



    Lasioglossum_semicaeruleum_f = list(Genus="Lasioglossum",
                                        SubGenus ="Dialictus",
                                        Species="semicaeruleum",
                                        SubSpecies="", Sex="f",
                                        Author ="Cockerell",
                                        Determiner = "J. Gardener",
                                        temp.id= c("17945", "17957",
                                                   "17958", "18201",
                                                   "18230", "18150")),

    Lasioglossum_semicaeruleum_m = list(Genus="Lasioglossum",
                                        SubGenus ="Dialictus",
                                        Species="semicaeruleum",
                                        SubSpecies="", Sex="m",
                                        Author ="Cockerell",
                                        Determiner = "J. Gardener",
                                        temp.id= c("17990")),



    Halictus_rubicundus_m= list(Genus="Halictus",
                                SubGenus ="Protohalictus",
                                Species="rubicundus",
                                SubSpecies="", Sex="m",
                                Author = "Christ",
                                Determiner = "D. Yanega",
                                temp.id= c("18708", "17807",
                                           "18307", "17660")),

    Lasioglossum_ruidosense_f= list(Genus="Lasioglossum",
                                    SubGenus ="Dialictus",
                                    Species="ruidosense",
                                    SubSpecies="cf.",
                                    Sex="f",
                                    Author = "Cockerell",
                                    Determiner = "J. Gardener",
                                    temp.id=c("17649", "18273",
                                              "18699", "18534",
                                              "17806", "17667",
                                              "18272", "18118",
                                              "17973", "18696",
                                              "18282", "18074",
                                              "18409", "18052",
                                              "18072", "17788",
                                              "18274", "17729",
                                              "18560", "18502",
                                              "18395", "18498")),

    Lasioglossum_ruidosense_m= list(Genus="Lasioglossum", SubGenus
                                    ="Dialictus", Species="ruidosense",
                                    SubSpecies="cf.", Sex="m",
                                    Author = "Cockerell",
                                    Determiner = "J. Gardener",
                                    temp.id=c("18265", "18266",
                                              "18710", "18564",
                                              "18075", "17690",
                                              "17675", "18548",
                                              "17724", "17653",
                                              "18245", "18261",
                                              "17661", "18262",
                                              "18246", "18722",
                                              "18573", "18258")),


    Lasioglossum_pacatum_viridatulum_f=
        list(Genus="Lasioglossum",
             SubGenus="Dialictus",
             Species="pacatum/viridatulum",
             SubSpecies="", Sex="f",
             Author = "",
             Determiner="J. Gardener",
             temp.id=c("18077", "18367",
                       "18685", "18339", "18277",
                       "18280", "18113", "18506",
                       "18303", "18308", "18304",
                       "18290", "18293", "18061",
                       "18509", "18366")),

    Lasioglossum_pacatum_viridatulum_m=
        list(Genus="Lasioglossum",
             SubGenus="Dialictus",
             Species="pacatum/viridatulum",
             SubSpecies="", Sex="m",
             Author = "",
             Determiner="J. Gardener",
             temp.id=c("18431", "18322",
                       "18320", "18365", "18073",
                       "18511")),

    Lasioglossum_obnubilum_f= list(Genus="Lasioglossum",
                                   SubGenus ="Dialictus",
                                   Species="obnubilum",
                                   SubSpecies="",
                                   Sex="f",
                                   Author = "Sandhouse",
                                   Determiner = "J. Gardener",
                                   temp.id= c("18698", "18572", "17662")),

    Lasioglossum_obnubilum_m= list(Genus="Lasioglossum",
                                   SubGenus ="Dialictus",
                                   Species="obnubilum",
                                   SubSpecies="",
                                   Sex="m",
                                   Author = "Sandhouse",
                                   Determiner = "J. Gardener",
                                   temp.id= c("18547")),


    Lasioglossum_laevissimum= list(Genus="Lasioglossum", SubGenus
                                   ="Dialictus",
                                   Species="laevissimum",
                                   SubSpecies="", Sex="f",
                                   Author = "Smith",
                                   Determiner = "J. Gardener",
                                   temp.id= c("18545", "18576",
                                              "18571", "18540"))



)
