
sp.ids <- list(

    Anthidium_maculosum_f = list(Genus="Anthidium",
                                 SubGenus ="Anthidium",
                                 Species="maculosum",
                                 SubSpecies="", Sex="f",
                                 Author = "Cresson",
                                 Determiner = "K. Watrous",
                                 temp.id= c("17879", "17741", "17715",
                                            "17721", "17714", "17683",
                                            "17701", "17686", "17682",
                                            "18042", "18190", "18176",
                                            "18263", "23927", "19017")),

    Anthidium_maculosum_m = list(Genus="Anthidium",
                                 SubGenus ="Anthidium",
                                 Species="maculosum",
                                 SubSpecies="", Sex="m",
                                 Author = "Cresson",
                                 Determiner = "K. Watrous",
                                 temp.id= c("17743", "17737", "17725",
                                            "17734", "17700", "18189",
                                            "18268", "23923", "23919")),

    Anthidium_tenuiflorae = list(Genus="Anthidium",
                                 SubGenus ="",
                                 Species="tenuiflorae",
                                 SubSpecies="", Sex="f",
                                 Author = "Cockerell",
                                 Determiner = "J.L. Neff",
                                 temp.id= c("20268", "19701")),

    Paranthidium_jugatorium = list(Genus="Paranthidium",
                                SubGenus ="",
                                Species="jugatorium",
                                SubSpecies="", Sex="m",
                                Author = "Say",
                                Determiner = "J.L. Neff",
                                temp.id= c("17769")),
    
    Megachile_agustini_f = list(Genus="Megachile",
                              SubGenus ="",
                              Species="agustini", SubSpecies="",
                              Sex="f",
                              Author = "Cockerell",
                              Determiner = "J.L. Neff",
                              temp.id= c("19571")),
    
    Megachile_fidelis_f = list(Genus="Megachile",
                               SubGenus ="Sayapis",
                               Species="fidelis",
                               SubSpecies="",
                               Sex="f",
                               Author = "Cresson",
                               Determiner = "K. Watrous",
                               temp.id= c("17937", 
                               "18227",
                                          "20431", "20433")),
    
    Megachile_fidelis_m = list(Genus="Megachile",
                               SubGenus ="Sayapis",
                               Species="fidelis",
                               SubSpecies="",
                               Sex="m",
                               Author = "Cresson",
                               Determiner = "T. Griswold",
                               temp.id= c("17904", "18504")),

    Megachile_frigida_f = list(Genus="Megachile",
                               SubGenus ="Xanthosarus",
                               Species="frigida",
                               SubSpecies="",
                               Sex="f", Author = "Smith",
                               Determiner = "T. Griswold",
                               temp.id=  c("20650",
                                           "20646",
                                           "20648",
                                           "20460",
                                           "20647",
                                           "20426",
                                           "20463",
                                           "20459",
                                           "20574",
                                           "20759",
                                           "20694",
                                           "20649",
                                           "20427")),

    Megachile_frigida_m = list(Genus="Megachile",
                               SubGenus ="Xanthosarus",
                               Species="frigida",
                               SubSpecies="",
                               Sex="m", Author = "Smith",
                               Determiner = "K. Watrous",
                               temp.id=  c("20437", "20428", "20429",
                                           "20562", "20436", "20503", "20760")),

    Megachile_gemula_f = list(Genus="Megachile",
                           SubGenus ="Xanthosarus",
                               Species="gemula",
                               SubSpecies="fulvogemula",
                              Sex="f", Author = "Cresson",
                               Determiner = "T. Griswold",
                               temp.id=  c("18717",
                                           "20505")),
    
    Megachile_subexilis_f = list(Genus="Megachile",
                              SubGenus ="Chelostomoides",
                              Species="subexilis",
                              SubSpecies="",
                              Sex="f", Author = "Cockerell",
                              Determiner = "T. Griswold",
                              temp.id=  c("18168",
                                          "18204",
                                          "17925",
                                          "20560",
                                          "18001",
                                          "18205",
                                          "17984",
                                          "18218",
                                          "17985",
                                          "18585",
                                          "17995",
                                          "18008",
                                          "18188",
                                          "20559",
                                          "20561")),


    Megachile_mellitarsis_f = list(Genus="Megachile",
                                   SubGenus ="Sayapis",
                                   Species="mellitarsis",
                                   SubSpecies="", Sex="f",
                                   Author = "Cresson",
                                   Determiner = "K. Watrous",
                                   temp.id= c("18224")),

    Heriades_cressoni_f = list(Genus="Heriades",
                               SubGenus ="Neotrypetes",
                               Species="cressoni",
                               SubSpecies="", Sex="f",
                               Author = "Michener",
                               Determiner = "L.C. Ponisio",
                               temp.id= c("18132", "18049", "18090",
                                          "18521", "18662", "18517")),
    
    Megachile_melanophaea_rohweri_m = list(Genus="Megachile",
                                           SubGenus ="Xanthosarus", Species="melanophaea",
                                           SubSpecies="rohweri",
                                           Sex="m", Author = "Smith",
                                           Determiner = "T. Griswold",
                                           temp.id= c("18034")),
    
    
    Megachile_melanophaea_rohweri_f = list(Genus="Megachile",
                                           SubGenus ="Xanthosarus", Species="melanophaea",
                                           SubSpecies="rohweri",
                                           Sex="f", Author = "Smith",
                                           Determiner = "T. Griswold",
                                           temp.id= c("20708")),
    
    Megachile_zapoteca_m = list(Genus="Megachile",
                                           SubGenus ="Cressoniella", Species="zapoteca",
                                           SubSpecies="",
                                           Sex="m", Author = "Cresson",
                                           Determiner = "T. Griswold",
                                           temp.id= c("18746")),
    
    Megachile_inimica_m = list(Genus="Megachile",
                               SubGenus ="Sayapis",
                               Species="inimica",
                               SubSpecies="sayi",
                               Sex="m", Author = "Cresson",
                               Determiner = "T. Griswold",
                               temp.id=  c("17913")),
    
    
    Megachile_mellitarsis_f = list(Genus="Megachile",
                                   SubGenus ="Sayapis", Species="mellitarsis",
                                   SubSpecies="", Sex="f",
                                   Author = "Cresson", Determiner = "T. Griswold",
                                   temp.id= c("20430")),
    
    Megachile_mellitarsis_m = list(Genus="Megachile",
                                   SubGenus ="Sayapis", Species="mellitarsis",
                                   SubSpecies="", Sex="m",
                                   Author = "Cresson", Determiner = "T. Griswold",
                                   temp.id= c("20465")),
    
    Megachile_comata_f = list(Genus="Megachile", SubGenus ="Xanthosarus",
                              Species="comata", SubSpecies="",
                              Sex="f",
                              Author = "Cresson", Determiner = "T. Griswold",
                              temp.id= c("20595",
                                         "17674",
                                         "20563",
                                         "20464",
                                         "20617",
                                         "20767",
                                         "20576",
                                         "20597",
                                         "20575")),
    
    Megachile_comata_m = list(Genus="Megachile", SubGenus ="Xanthosarus",
                              Species="comata", SubSpecies="",
                              Sex="m",
                              Author = "Cresson", Determiner = "T. Griswold",
                              temp.id= c("20792",
                                         "20758")),
    
    Megachile_relativa_f = list(Genus="Megachile",
                                SubGenus ="Megachile", Species="relativa",
                                SubSpecies="", Sex="f",
                                Author = "Cresson", Determiner = "T. Griswold",
                                temp.id= c("20434",
                                           "20462",
                                           "20432",
                                           "18111",
                                           "20425"))


)
