
sp.ids <- list(


    ##   Pseudopanurgus_piercei_f= list(Genus="Pseudopanurgus",
    ##                                   SubGenus ="",
    ##                                   Species="piercei",
    ##                                   SubSpecies="",
    ##                                   Sex="f", Author = "Crawford",
    ##                                   Determiner="",
    ##                                   temp.id= c()),


     Pseudopanurgus_atricornis_f= list(Genus="Pseudopanurgus",
                                       SubGenus ="",
                                       Species="atricornis",
                                       SubSpecies="",
                                       Sex="f", Author = "Cresson",
                                       Determiner="J.L. Neff",
                                       temp.id= c(33356, 33357, 33367,
                                                 33352, 33365)),


     Pseudopanurgus_atricornis_m= list(Genus="Pseudopanurgus",
                                       SubGenus ="",
                                       Species="atricornis",
                                       SubSpecies="",
                                       Sex="m", Author = "Cresson",
                                       Determiner="",
                                       temp.id= c(33482, 33484, 33473,
                                                 33361, 33390, 33385,
                                                 33362, 33617, 33164,
                                                 33170, 33152, 33143,
                                                 33845, 33169, 33266,
                                                 33267, 33853, 33259,
                                                 33283, 33204, 33200,
                                                 32307, 33255, 33201,
                                                 33218, 31887, 33154,
                                                 33253, 33261, 33265,
                                                 33960, 33968, 33850,
                                                 33373, 33622, 33384,
                                                 33374, 33350, 33349,
                                                 33345, 33344, 33368,
                                                 33369, 33874, 33957,
                                                 33875, 33880, 33462,
                                                 33975, 33971, 33377,
                                                 33859, 33860, 33879,
                                                 33948, 33950, 33872,
                                                 33868, 33339, 33457,
                                                 30642, 32590,
                                                 33270, 33976, 33165,
                                                 33167, 33153, 33291,
                                                 33276, 33159, 32583,
                                                 33338, 33160, 33340,
                                                 32604, 37838, 33343,
                                                 33172, 33978, 33287,
                                                 32308,
                                                 33354, 33279, 33465,
                                                 33376, 33380, 33208,
                                                 33282, 33269)),
    
    Pseudopanurgus_albitarsis_f= list(Genus="Pseudopanurgus", SubGenus ="",
                                      Species="albitarsis",
                                      SubSpecies="",
                                      Sex="f", Author = "Cresson, 1872",
                                      Determiner="J.L. Neff",
                                      temp.id= c(33071, 32892, 32891,
                                                 32896, 33109, 32895,
                                                 33113,
                                                 33490,
                                                 34070,
                                                 33086, 32903, 32811,
                                                 33068, 33072, 33073,
                                                 33095, 33097, 32910,
                                                 33094, 32899, 32909,
                                                 32905, 32904, 33065,
                                                 32810, 33079, 32901,
                                                 33074, 33063, 33088,
                                                 33087, 33077, 33078,
                                                 33064, 33091)),
    
    Pseudopanurgus_albitarsis_m= list(Genus="Pseudopanurgus", SubGenus ="",
                                      Species="albitarsis",
                                      SubSpecies="",
                                      Sex="m", Author = "Cresson, 1872",
                                      Determiner="J.L. Neff",
                                      temp.id= c(33059, 33090,
                                                 33092,
                                                 33089, 33083, 33084,
                                                 33085, 33107, 
                                                 33066, 33105,
                                                 33082, 33075, 32834,
                                                 32886, 33067, 32835,
                                                 33093, 32893,
                                                 33069, 33080, 33081,
                                                 32894, 32906, 33070,
                                                 32900, 32902, 32897,
                                                 33106, 33104,
                                                 33060, 33062, 33100,
                                                 32890, 33101, 33098,
                                                 33112, 32888, 32889,
                                                 32887, 33103, 33114,
                                                 33076, 33102, 32812,
                                                 32907, 32898, 33096)),

    ##   Panurginus_cressoniellus_f= list(Genus="Panurginus", SubGenus ="",
    ##                                  Species="cressoniellus",
    ##                                  SubSpecies="",
    ##                                  Sex="f", Author = "Cockerell",
    ##                                  Determiner=,
    ##                                  temp.id= c()),


    ## Protandrena_sp_a= list(Genus="Protandrena", SubGenus ="",
    ##                        Species="sp.",
    ##                        SubSpecies="a",
    ##                        Sex="f", Author = "",
    ##                        Determiner=,
    ##                        temp.id= c()),


    ## Protandrena_sp_c= list(Genus="Protandrena", SubGenus ="",
    ##                        Species="sp.",
    ##                        SubSpecies="c",
    ##                        Sex="m", Author = "",
    ##                        Determiner="",
    ##                        temp.id= c()),

    ##     Protandrena_sp_d= list(Genus="Protandrena", SubGenus ="",
    ##                        Species="sp.",
    ##                        SubSpecies="d",
    ##                        Sex="f", Author = "",
    ##                        Determiner="",
    ##                        temp.id= c()),

    ##   Protandrena_sp_d= list(Genus="Protandrena", SubGenus ="",
    ##                        Species="sp.",
    ##                        SubSpecies="d",
    ##                        Sex="m", Author = "",
    ##                        Determiner="",
    ##                        temp.id= c()),

    ##   Protandrena_sp_d= list(Genus="Protandrena", SubGenus ="",
    ##                        Species="sp.",
    ##                        SubSpecies="e",
    ##                        Sex="m", Author = "",
    ##                        Determiner="",
    ##                        temp.id= c()),



    ## Pseudopanurgus_porterae_f= list(Genus="Pseudopanurgus",
    ##                             SubGenus ="",
    ##                             Species="porterae",
    ##                             SubSpecies="",
    ##                             Sex="f",
    ##                             Author = "Cockerell",
    ##                             Determiner="",
    ##                             temp.id= c()),



    ## Pseudopanurgus_porterae_m= list(Genus="Pseudopanurgus",
    ##                             SubGenus ="",
    ##                             Species="porterae",
    ##                             SubSpecies="",
    ##                             Sex="m",
    ##                             Author = "Cockerell",
    ##                             Determiner="",
    ##                             temp.id= c()),



    ## Andrena_argemonis_f = list(Genus="Andrena",
    ##                            SubGenus="Plastandrena",
    ##                            Species="argemonis",
    ##                            SubSpecies="",
    ##                            Sex="f", Author = "Cockerell",
    ##                            Determiner="",
    ##                            temp.id= c()),

    ## Andrena_argemonis_m = list(Genus="Andrena",
    ##                            SubGenus="Plastandrena",
    ##                            Species="argemonis",
    ##                            SubSpecies="",
    ##                            Sex="m", Author = "Cockerell",
    ##                            Determiner="",
    ##                            temp.id= c()),


    ## Heterosarus_bakeri_f= list(Genus="Heterosarus",
    ##                            SubGenus ="",
    ##                            Species="bakeri",
    ##                            SubSpecies="",
    ##                            Sex="f",
    ##                            Author = "Cockerell",
    ##                            Determiner="",
    ##                            temp.id= c()),



    ## Heterosarus_bakeri_m= list(Genus="Heterosarus",
    ##                            SubGenus ="",
    ##                            Species="bakeri",
    ##                            SubSpecies="",
    ##                            Sex="m",
    ##                            Author = "Cockerell",
    ##                            Determiner="",
    ##                            temp.id= c(
    ##                            )),


    ## Heterosarus_neomex_f= list(Genus="Heterosarus",
    ##                            SubGenus ="",
    ##                            Species="neomexicanus",
    ##                            SubSpecies="",
    ##                            Sex="f",
    ##                            Author = "Cockerell",
    ##                            Determiner="",
    ##                            temp.id= c()),

    ## Panurginus_sp_a_f= list(Genus="Panurginus", SubGenus ="",
    ##                         Species="sp.",
    ##                         SubSpecies="a",
    ##                         Sex="f", Author = "",
    ##                         Determiner="",
    ##                         temp.id= c()),

    ## Panurginus_cressoniellus_f= list(Genus="Panurginus",
    ##                                  SubGenus ="",
    ##                                  Species="cressoniellus",
    ##                                  SubSpecies="",
    ##                                  Sex="f", Author = "Cockerell",
    ##                                  Determiner="",
    ##                                  temp.id= c()),

    ## Triepeolus_sp_a_m= list(Genus="Triepeolus",
    ##                         SubGenus="",
    ##                         Species="sp.",
    ##                         SubSpecies="a",
    ##                         Sex="m",
    ##                         Author = "",
    ##                         Determiner="",
    ##                         temp.id= c(
    ##                         )),



    ## Triepeolus_sp_a_f= list(Genus="Triepeolus",
    ##                         SubGenus="",
    ##                         Species="sp.",
    ##                         SubSpecies="a",
    ##                         Sex="f",
    ##                         Author = "",
    ##                         Determiner="",
    ##                         temp.id= c( )),

    ## Triepeolus_sp_b_f= list(Genus="Triepeolus",
    ##                         SubGenus="",
    ##                         Species="sp.",
    ##                         SubSpecies="b",
    ##                         Sex="f",
    ##                         Author = "",
    ##                         Determiner="",
    ##                         temp.id= c()),


    Andrena_apacheorum_f= list(Genus="Andrena",
                               SubGenus ="Cnemidandrena",
                               Species="apacheorum",
                               SubSpecies="",
                               Sex="f",
                               Author = "Cockerell",
                               Determiner="J.L. Neff",
                               temp.id= c(31370, 31590, 31587, 31671,
                                         31669, 31670, 31531, 33058, 31222,
                                         32286, 33146, 30644, 33148, 33147,
                                         33157, 33335, 33382, 33939, 33940,
                                         33944, 33946, 33947, 33334, 31244,
                                         30931, 31374, 32287, 31920, 31897,
                                         31903, 32289, 32529, 31228)),

     Andrena_apacheorum_m= list(Genus="Andrena",
                                SubGenus ="Cnemidandrena",
                                Species="apacheorum",
                                SubSpecies="",
                                Sex="m",
                                Author = "Cockerell",
                                Determiner="J.L. Neff",
                                temp.id= c(31525, 31218, 33861)),

    ## Andrena_costillensis= list(Genus="Andrena",
    ##                            SubGenus ="Cnemidandrena",
    ##                            Species="costillensis",
    ##                            SubSpecies="",
    ##                            Sex="f",
    ##                            Author =
    ##                                "Viereck \\& Cockerell",
    ##                            Determiner="",
    ##                            temp.id= c())

    Xylocopa_californica_f= list(Genus="Xylocopa",
                                 SubGenus ="Xylocopoides",
                                 Species="californica",
                                 SubSpecies="",
                                 Sex="f",
                                 Author =
                                     "Cresson",
                                 Determiner="L. Ponisio",
                                 temp.id= c(33995)),


     Andrena_birtwelli_f= list(Genus="Andrena",
                                 SubGenus ="",
                                 Species="birtwelli",
                                 SubSpecies="",
                                 Sex="f",
                                 Author = "Cockerell",
                                 Determiner="J.L. Neff",
                                 temp.id= c(31598, 31593, 31596, 31597, 31595,
                                           31594, 31660, 31662, 31663, 31661,
                                           31665, 31664, 31666, 31667, 31668,
                                           31712, 31713, 31716, 31174, 31715,
                                           31717, 31718, 31719, 31720, 31585,
                                           31721, 31722, 31723, 31724, 31584,
                                           31586, 31588, 31583, 31725, 31728,
                                           31729, 31731, 31727, 31726, 31736,
                                           31734, 31735, 31733, 31737, 31732,
                                           31730, 31738, 31740, 31741, 31739,
                                           31742, 31743, 31744, 31745, 31746,
                                           31747, 31748, 31749, 31751, 31753,
                                           31752, 31754, 31755, 31591, 31756,
                                           31589, 31757, 31544, 31469, 31543,
                                           31542, 31541, 31540, 31539, 31538,
                                           31537, 31536, 31573, 31535, 31534,
                                           31533, 31532, 31530, 31529, 31528,
                                           31527, 31526, 31574, 31575, 31576,
                                           31577, 31784, 31570, 31568, 31783,
                                           31782, 31781, 31572, 31779, 31780,
                                           31777, 31567, 31565, 31778, 31564,
                                           31776, 31775, 31563, 31562, 31774,
                                           31561, 31773, 31560, 31772, 31771,
                                           31559, 31558, 31770, 31557, 31364,
                                           31768, 31556, 31225, 31555, 31217,
                                           31769, 31592, 31767, 31554, 31221,
                                           31766, 31553, 32528, 31578, 31864,
                                           31552, 32527, 31765, 31551, 31478,
                                           31764, 32662, 31763, 32526, 31550,
                                           32398, 32388, 31549, 31762, 31548,
                                           31761, 31582, 31760, 31547, 31759,
                                           31546, 31545, 31758, 32661, 32663,
                                           31786, 31785, 31581, 31580, 31579)),

     Andrena_birtwelli_m= list(Genus="Andrena",
                                 SubGenus ="",
                                 Species="birtwelli",
                                 SubSpecies="",
                                 Sex="m",
                                 Author = "Cockerell",
                                 Determiner="J.L. Neff",
                                 temp.id= c(31379, 31224, 31571)),


     Andrena_tegularis_f= list(Genus="Andrena",
                                 SubGenus ="",
                                 Species="tegularis",
                                 SubSpecies="",
                                 Sex="f",
                                 Author = "LaBerge",
                                 Determiner="J.L. Neff",
                                 temp.id= c(34064, 34016, 34230, 34227, 34171,
                                           34086, 34170, 34062, 34099, 34165,
                                           34169)),

     Andrena_tegularis_m= list(Genus="Andrena",
                                 SubGenus ="",
                                 Species="tegularis",
                                 SubSpecies="",
                                 Sex="m",
                                 Author = "LaBerge",
                                 Determiner="J.L. Neff",
                                 temp.id= c(34222, 34197)),


     Andrena_hitei_f= list(Genus="Andrena",
                                 SubGenus ="",
                                 Species="hitei",
                                 SubSpecies="",
                                 Sex="f",
                                 Author = "Cockerell",
                                 Determiner="J.L. Neff",
                                 temp.id= c(31974)),

     Andrena_pecosana_f= list(Genus="Andrena",
                                 SubGenus ="",
                                 Species="pecosana",
                                 SubSpecies="",
                                 Sex="f",
                                 Author = "Cockerell",
                                 Determiner="J.L. Neff",
                                 temp.id= c(34093, 34101)),

     Andrena_pecosana_m= list(Genus="Andrena",
                                 SubGenus ="",
                                 Species="pecosana",
                                 SubSpecies="",
                                 Sex="m",
                                 Author = "Cockerell",
                                 Determiner="J.L. Neff",
                                 temp.id= c(34014, 34096, 33240)),

     Andrena_segregans_f= list(Genus="Andrena",
                                 SubGenus ="",
                                 Species="segregans",
                                 SubSpecies="",
                                 Sex="f",
                                 Author = "Cockerell",
                                 Determiner="J.L. Neff",
                                 temp.id= c(32301, 32290, 31916, 31912, 31882, 31895))

    )
