
sp.ids <- list(

    Anthidium_maculosum_f = list(Genus="Anthidium",
                                     SubGenus ="Anthidium",
                                     Species="maculosum",
                                     SubSpecies="", Sex="f",
                                     Author = "Cresson",
                                     Determiner = "J.L. Neff",
                                     temp.id= c(34317, 34174)),

    
    ## Anthidium_maculosum_m = list(Genus="Anthidium",
    ##                              SubGenus ="Anthidium",
    ##                              Species="maculosum",
    ##                              SubSpecies="", Sex="m",
    ##                              Author = "Cresson",
    ##                              Determiner = "",
    ##                              temp.id= c()),
    
    
    Anthidium_manicatum_m = list(Genus="Anthidium",
                                     SubGenus ="",
                                     Species="manicatum",
                                     SubSpecies="", Sex="m",
                                     Author = "Linnaeus",
                                     Determiner = "J.L. Neff",
                                     temp.id= c(30643)),

    
    Paranthidium_jugatorium_f = list(Genus="Paranthidium",
                                     SubGenus ="",
                                     Species="jugatorium",
                                     SubSpecies="", Sex="f",
                                     Author = "Say",
                                     Determiner = "J.L. Neff",
                                     temp.id= c(34065, 34018, 34128, 34020, 34019,
                                               34129, 34127)),
     
     
     Paranthidium_jugatorium_m = list(Genus="Paranthidium",
                                     SubGenus ="",
                                     Species="jugatorium",
                                     SubSpecies="", Sex="m",
                                     Author = "Say",
                                     Determiner = "J.L. Neff",
                                     temp.id= c(34130, 34182, 32772)),
    

     Coelioxys_rufitarsis_m = list(Genus="Coelioxys",
                                     SubGenus ="",
                                     Species="rufitarsis",
                                     SubSpecies="", Sex="m",
                                     Author = "Smith",
                                     Determiner = "J.L. Neff",
                                     temp.id= c(30799)),
    
    
     Coelioxys_sodalis_m = list(Genus="Coelioxys",
                                     SubGenus ="Coelioxys",
                                     Species="sodalis",
                                     SubSpecies="", Sex="m",
                                     Author = "Cresson",
                                     Determiner = "J.L. Neff",
                                     temp.id= c(30907)),
    
        
     Coelioxys_sodalis_f = list(Genus="Coelioxys",
                                     SubGenus ="Coelioxys",
                                     Species="sodalis",
                                     SubSpecies="", Sex="f",
                                     Author = "Cresson",
                                     Determiner = "J.L. Neff",
                                     temp.id= c(30909, 30908, 31132, 30910)),
    
    
    ## Lithurgopsis_apicalis_m = list(Genus="Lithurgopsis",
    ##                              SubGenus ="",
    ##                              Species="apicalis",
    ##                              SubSpecies="", Sex="m",
    ##                              Author = "Cresson",
    ##                              Determiner = "L. Best",
    ##                              temp.id= c()),

    
    Megachile_fidelis_f = list(Genus="Megachile",
                               SubGenus ="Sayapis",
                               Species="fidelis",
                               SubSpecies="",
                               Sex="f",
                               Author = "Cresson",
                               Determiner = "",
                               temp.id= c(33057, 33115)),

    ## Megachile_fidelis_m = list(Genus="Megachile",
    ##                            SubGenus ="Sayapis",
    ##                            Species="fidelis",
    ##                            SubSpecies="",
    ##                            Sex="m",
    ##                            Author = "Cresson",
    ##                            Determiner = "",
    ##                            temp.id= c()),

    Megachile_frigida_f = list(Genus="Megachile",
                               SubGenus ="Xanthosarus",
                               Species="frigida",
                               SubSpecies="",
                               Sex="f", Author = "Smith",
                               Determiner = "L. Best",
                               temp.id=  c(33021, 30641, 30640, 31042,
                                           31041, 31039, 30648)),

    ## Megachile_frigida_m = list(Genus="Megachile",
    ##                            SubGenus ="Xanthosarus",
    ##                            Species="frigida",
    ##                            SubSpecies="",
    ##                            Sex="m", Author = "Smith",
    ##                            Determiner = "",
    ##                            temp.id=  c(
    ##                            )),

    ## Megachile_gemula_f = list(Genus="Megachile",
    ##                           SubGenus ="Xanthosarus",
    ##                           Species="gemula",
    ##                           SubSpecies="fulvogemula",
    ##                           Sex="f", Author = "Cresson",
    ##                           Determiner = "",
    ##                           temp.id=  c()),

    ## Megachile_subexilis_f = list(Genus="Megachile",
    ##                              SubGenus ="Chelostomoides",
    ##                              Species="subexilis",
    ##                              SubSpecies="",
    ##                              Sex="f", Author = "Cockerell",
    ##                              Determiner = "",
    ##                              temp.id=  c()),


    ## Megachile_mellitarsis_f = list(Genus="Megachile",
    ##                                SubGenus ="Sayapis",
    ##                                Species="mellitarsis",
    ##                                SubSpecies="", Sex="f",
    ##                                Author = "Cresson",
    ##                                Determiner = "",
    ##                                temp.id= c()),

    ## Heriades_cressoni_f = list(Genus="Heriades",
    ##                            SubGenus ="Neotrypetes",
    ##                            Species="cressoni",
    ##                            SubSpecies="", Sex="f",
    ##                            Author = "Michener",
    ##                            Determiner = "",
    ##                            temp.id= c()),

    ## Megachile_melanophaea_rohweri_m = list(Genus="Megachile",
    ##                                        SubGenus ="Xanthosarus",
    ##                                        Species="melanophaea",
    ##                                        SubSpecies="rohweri",
    ##                                        Sex="m", Author = "Smith",
    ##                                        Determiner = "",
    ##                                        temp.id= c()),


    Megachile_melanophaea_rohweri_f = list(Genus="Megachile",
                                           SubGenus ="Xanthosarus",
                                           Species="melanophaea",
                                           SubSpecies="rohweri",
                                           Sex="f", Author = "Smith",
                                           Determiner = "L. Best",
                                           temp.id= c(
                                                      30761,
                                                      31457, 31355,
                                                      31204, 31194,
                                                      31458, 31978,
                                                      31185)),

    ## Megachile_zapoteca_m = list(Genus="Megachile",
    ##                             SubGenus ="Xanthosarus",
    ##                             Species="zapoteca",
    ##                             SubSpecies="",
    ##                             Sex="m", Author = "Cresson",
    ##                             Determiner = "",
    ##                             temp.id= c()),

    ## Megachile_inimica_m = list(Genus="Megachile",
    ##                            SubGenus ="Sayapis",
    ##                            Species="inimica",
    ##                            SubSpecies="sayi",
    ##                            Sex="m", Author = "Cresson",
    ##                            Determiner = "",
    ##                            temp.id=  c()),


    ## Megachile_mellitarsis_f = list(Genus="Megachile",
    ##                                SubGenus ="Sayapis",
    ##                                Species="mellitarsis",
    ##                                SubSpecies="", Sex="f",
    ##                                Author = "Cresson",
    ##                                Determiner = "",
    ##                                temp.id= c()),

    ## Megachile_mellitarsis_m = list(Genus="Megachile",
    ##                                SubGenus ="Sayapis",
    ##                                Species="mellitarsis",
    ##                                SubSpecies="", Sex="m",
    ##                                Author = "Cresson",
    ##                                Determiner = "",
    ##                                temp.id= c()),

    Megachile_comata_f = list(Genus="Megachile",
                              SubGenus ="Xanthosarus",
                              Species="comata",
                              SubSpecies="",
                              Sex="f",
                              Author = "Cresson",
                              Determiner = "L. Best",
                              temp.id= c(30903, 33142, 33178, 33179,
                                         33224, 33442, 33843, 33933)),

    Megachile_comata_m = list(Genus="Megachile",
                              SubGenus ="Xanthosarus",
                              Species="comata", SubSpecies="",
                              Sex="m",
                              Author = "Cresson",
                              Determiner = "L. Best",
                              temp.id= c()),

    ## Megachile_relativa_f = list(Genus="Megachile",
    ##                             SubGenus ="Megachile",
    ##                             Species="relativa",
    ##                             SubSpecies="", Sex="f",
    ##                             Author = "Cresson",
    ##                             Determiner = "",
    ##                             temp.id= c())

    Hoplitis_albifrons_m = list(Genus="Hoplitis",
                                SubGenus ="Alcidamea",
                                Species="albifrons",
                                SubSpecies="", Sex="m",
                                Author = "Kirby",
                                Determiner = "L. Best",
                                temp.id= c(30941, 30918)),

    Hoplitis_albifrons_f = list(Genus="Hoplitis",
                                SubGenus ="Alcidamea",
                                Species="albifrons",
                                SubSpecies="", Sex="f",
                                Author = "Kirby",
                                Determiner = "L. Best",
                                temp.id= c(30919)),

    Hoplitis_fulgida_f = list(Genus="Hoplitis",
                              SubGenus ="",
                              Species="fulgida",
                              SubSpecies="", Sex="f",
                              Author = "Cronquist",
                              Determiner = "L. Best",
                              temp.id= c(31360))

)
