
sp.ids <- list(
    Calliopsis_teucrii_f = list(Genus="Calliopsis",
                                SubGenus="Calliopsis",
                                Species="teucrii",
                                SubSpecies="",
                                Sex="f", Author = "Cockerell",
                                Determiner="L. Ponisio",
                                temp.id= c("BBSL1087251",
                                           "BBSL1072617",
                                           "BBSL1070696")),

    Calliopsis_teucrii_m = list(Genus="Calliopsis",
                                SubGenus="Calliopsis",
                                Species="teucrii",
                                SubSpecies="",
                                Sex="m", Author = "Cockerell",
                                Determiner="L. Ponisio",
                                temp.id= c("BBSL1084536",
                                           "BBSL1084524",
                                           "BBSL1084538",
                                           "BBSL1072620",
                                           "BBSL1072621")),

    Calliopsis_verbenae = list(Genus="Calliopsis",
                                      SubGenus ="",
                                      Species="verbenae",
                                      SubSpecies="",
                                      Sex="m", Author = "Cockerell and Porter",
                                      Determiner="J.L. Neff",
                                      temp.id= c("22423")),

    Andrena_prunorum_f = list(Genus="Andrena",
                              SubGenus="Plastandrena",
                              Species="prunorum",
                              SubSpecies="",
                              Sex="f",
                              Author = "Cockerell",
                              Determiner="L. Ponisio",
                              temp.id= c("BBSL1087151")),

    Andrena_apacheorum_f= list(Genus="Andrena", SubGenus ="Cnemidandrena",
                               Species="apacheorum",
                               SubSpecies="",
                               Sex="f",
                               Author = "Cockerell",
                               Determiner="D. Yanega",
                               temp.id= c("BBSL1085675",
                                          "BBSL1085791",
                                          "BBSL1074089",
                                          "BBSL1071511",
                                          "BBSL1059002",
                                          "BBSL1070648",
                                          "BBSL1070251",
                                          "BBSL1070362",
                                          "BBSL1070303",
                                          "BBSL1074431")),

    Andrena_apacheorum_m= list(Genus="Andrena", SubGenus ="Cnemidandrena",
                               Species="apacheorum",
                               SubSpecies="",
                               Sex="m",
                               Author = "Cockerell",
                               Determiner="D. Yanega",
                               temp.id= c("BBSL1085802",
                                          "BBSL1085792",
                                          "BBSL1085826",
                                          "BBSL1059318",
                                          "BBSL1070314",
                                          "BBSL1074415",
                                          "BBSL1070284",
                                          "BBSL1074362",
                                          "BBSL1070252")),

    
    Protandrena_sp_b= list(Genus="Protandrena", SubGenus ="",
                           Species="n. sp.",
                           SubSpecies="b",
                           Sex="f", Author = "",
                           Determiner="D. Yanega",
                           temp.id= c("BBSL1086888")),



    Panurginus_cressoniellus_f= list(Genus="Panurginus", SubGenus ="",
                                     Species="cressoniellus",
                                     SubSpecies="",
                                     Sex="f", Author = "Cockerell",
                                     Determiner="D. Yanega",
                                     temp.id= c(
                                         "BBSL1070195",
                                         "BBSL1070631",
                                         "BBSL1070587",
                                         "BBSL1070665",
                                         "BBSL1070663",
                                         "BBSL1058679",
                                         "BBSL1070196",
                                         "BBSL1058773",
                                         "BBSL1070625",
                                         "BBSL1070194",
                                         "BBSL1087283",
                                         "BBSL1087265",
                                         "BBSL1084794",
                                         "BBSL1087268")),


    Panurginus_cressoniellus_m= list(Genus="Panurginus", SubGenus ="",
                                     Species="cressoniellus",
                                     SubSpecies="",
                                     Sex="m", Author = "Cockerell",
                                     Determiner="D. Yanega",
                                     temp.id= c(
                                         "BBSL1071096",
                                         "BBSL1071099",
                                         "BBSL1071037",
                                         "BBSL1071059",
                                         "BBSL1071112",
                                         "BBSL1073437",
                                         "BBSL1073462",
                                         "BBSL1071054",
                                         "BBSL1058724",
                                         "BBSL1084803",
                                         "BBSL1084548",
                                         "BBSL1084770",
                                         "BBSL1084767",
                                         "BBSL1084755",
                                         "BBSL1071078",
                                         "BBSL1084805",
                                         "BBSL1084742",
                                         "BBSL1058707",
                                         "21696"
                                     )),

    Pseudopanurgus_atricornis_f= list(Genus="Pseudopanurgus",
                                      SubGenus ="",
                                      Species="atricornis",
                                      SubSpecies="",
                                      Sex="f", Author = "Cresson",
                                      Determiner="D. Yanega",
                                      temp.id= c("BBSL1085975",
                                                 "BBSL1085967",
                                                 "BBSL1085969",
                                                 "BBSL1085694",
                                                 "BBSL1085748",
                                                 "BBSL1085908",
                                                 "BBSL1085968",
                                                 "BBSL1085937",
                                                 "BBSL1085162",
                                                 "BBSL1086542",
                                                 "BBSL1084897",
                                                 "BBSL1085236",
                                                 "BBSL1085356",
                                                 "BBSL1085394",
                                                 "BBSL1085319",
                                                 "BBSL1084912",
                                                 "BBSL1084906",
                                                 "BBSL1085994",
                                                 "BBSL1085454",
                                                 "BBSL1086019",
                                                 "BBSL1086039",
                                                 "BBSL1085112",
                                                 "BBSL1059369",
                                                 "BBSL1071786",
                                                 "BBSL1071788",
                                                 "BBSL1071789",
                                                 "BBSL1071790",
                                                 "BBSL1074187",
                                                 "BBSL1074029",
                                                 "BBSL1074030",
                                                 "BBSL1074021",
                                                 "BBSL1074284",
                                                 "BBSL1074289",
                                                 "BBSL1074290",
                                                 "BBSL1074060",
                                                 "BBSL1074055",
                                                 "BBSL1071792",
                                                 "BBSL1071797",
                                                 "BBSL1070675",
                                                 "BBSL1058207",
                                                 "BBSL1059683",
                                                 "BBSL1059676",
                                                 "BBSL1071783",
                                                 "BBSL1059577",
                                                 "BBSL1073893",
                                                 "BBSL1059837",
                                                 "BBSL1071666",
                                                 "BBSL1074279",
                                                 "BBSL1074403",
                                                 "BBSL1071643",
                                                 "BBSL1071660",
                                                 "BBSL1074353",
                                                 "BBSL1073928",
                                                 "BBSL1071368",
                                                 "BBSL1071369",
                                                 "BBSL1074400",
                                                 "BBSL1074412",
                                                 "BBSL1071513",
                                                 "BBSL1071314",
                                                 "BBSL1070232",
                                                 "BBSL1074411",
                                                 "BBSL1070231",
                                                 "BBSL1074218",
                                                 "BBSL1074022",
                                                 "BBSL1074051",
                                                 "BBSL1074281",
                                                 "BBSL1073958",
                                                 "BBSL1071753",
                                                 "BBSL1071748",
                                                 "BBSL1071768",
                                                 "BBSL1071749",
                                                 "BBSL1074240",
                                                 "BBSL1071750",
                                                 "BBSL1074243",
                                                 "BBSL1071767",
                                                 "BBSL1074177",
                                                 "BBSL1071682",
                                                 "BBSL1071683",
                                                 "BBSL1073891",
                                                 "BBSL1074061",
                                                 "BBSL1071699",
                                                 "BBSL1074248",
                                                 "BBSL1071739",
                                                 "BBSL1074178",
                                                 "BBSL1071704",
                                                 "BBSL1074410",
                                                 "BBSL1071684",
                                                 "BBSL1071674",
                                                 "BBSL1071724",
                                                 "BBSL1071703",
                                                 "BBSL1071714",
                                                 "BBSL1071717",
                                                 "BBSL1071718",
                                                 "BBSL1071719",
                                                 "BBSL1071743",
                                                 "BBSL1074277",
                                                 "BBSL1074285",
                                                 "BBSL1073910",
                                                 "BBSL1073911",
                                                 "BBSL1070304",
                                                 "BBSL1074057",
                                                 "BBSL1074186",
                                                 "BBSL1074058",
                                                 "BBSL1074062",
                                                 "BBSL1074056",
                                                 "BBSL1071814",
                                                 "BBSL1074052",
                                                 "BBSL1071818",
                                                 "BBSL1071806",
                                                 "BBSL1071766",
                                                 "BBSL1071765",
                                                 "BBSL1071825",
                                                 "BBSL1070664",
                                                 "BBSL1071770",
                                                 "BBSL1071772",
                                                 "BBSL1071764",
                                                 "BBSL1071773",
                                                 "BBSL1085450",
                                                 "20882","21210","21180","22351")),

    Pseudopanurgus_atricornis_m= list(Genus="Pseudopanurgus",
                                      SubGenus ="",
                                      Species="atricornis",
                                      SubSpecies="",
                                      Sex="m", Author = "Cresson",
                                      Determiner="D. Yanega",
                                      temp.id= c("BBSL1086444",
                                                 "BBSL1086699",
                                                 "BBSL1086816",
                                                 "BBSL1086031",
                                                 "BBSL1085358",
                                                 "BBSL1085938",
                                                 "BBSL1074280",
                                                 "BBSL1086752",
                                                 "BBSL1085955",
                                                 "BBSL1086427",
                                                 "BBSL1086639",
                                                 "BBSL1085902",
                                                 "BBSL1070578",
                                                 "BBSL1074292",
                                                 "BBSL1074288",
                                                 "BBSL1074413",
                                                 "BBSL1073998",
                                                 "BBSL1071535",
                                                 "BBSL1071315",
                                                 "BBSL1074129",
                                                 "BBSL1071359",
                                                 "BBSL1070366",
                                                 "BBSL1071464",
                                                 "BBSL1070367",
                                                 "BBSL1074402",
                                                 "BBSL1074363",
                                                 "BBSL1071644",
                                                 "BBSL1071370",
                                                 "BBSL1074252",
                                                 "BBSL1074401",
                                                 "BBSL1074023",
                                                 "BBSL1074031",
                                                 "BBSL1070319",
                                                 "BBSL1074032",
                                                 "BBSL1071771",
                                                 "BBSL1073956",
                                                 "BBSL1071807",
                                                 "BBSL1071776",
                                                 "BBSL1071828",
                                                 "BBSL1071817",
                                                 "BBSL1071787",
                                                 "BBSL1071827",
                                                 "BBSL1071775",
                                                 "BBSL1071371",
                                                 "BBSL1071774",
                                                 "BBSL1071675",
                                                 "BBSL1071726",
                                                 "BBSL1071745",
                                                 "BBSL1058205",
                                                 "BBSL1071752",
                                                 "BBSL1071747",
                                                 "BBSL1071725",
                                                 "BBSL1071740",
                                                 "BBSL1071791",
                                                 "BBSL1070558",
                                                 "BBSL1071489",
                                                 "BBSL1074054",
                                                 "BBSL1058623",
                                                 "BBSL1058206",
                                                 "BBSL1074327",
                                                 "BBSL1070305",
                                                 "BBSL1074053",
                                                 "BBSL1074244",
                                                 "BBSL1074270",
                                                 "BBSL1074123",
                                                 "BBSL1071701",
                                                 "BBSL1071798",
                                                 "BBSL1071472",
                                                 "BBSL1071514",
                                                 "BBSL1058604",
                                                 "BBSL1059413",
                                                 "BBSL1071751",
                                                 "BBSL1074122")),



    Heterosarus_bakeri_f= list(Genus="Heterosarus",
                               SubGenus ="",
                               Species="bakeri",
                               SubSpecies="",
                               Sex="f",
                               Author = "Cockerell",
                               Determiner="D. Yanega",
                               temp.id= c("BBSL1085403",
                                          "BBSL1086548",
                                          "BBSL1086451",
                                          "BBSL1086471",
                                          "BBSL1085429",
                                          "BBSL1086460",
                                          "BBSL1086473",
                                          "BBSL1086412",
                                          "BBSL1086590",
                                          "BBSL1086565",
                                          "BBSL1086496",
                                          "BBSL1086608",
                                          "BBSL1086027",
                                          "BBSL1085352",
                                          "BBSL1085363",
                                          "BBSL1084722",
                                          "BBSL1071612",
                                          "BBSL1085342",
                                          "BBSL1085317",
                                          "BBSL1084963",
                                          "BBSL1085334",
                                          "BBSL1085018",
                                          "BBSL1085375",
                                          "BBSL1086537",
                                          "BBSL1085332",
                                          "BBSL1086774",
                                          "BBSL1085348",
                                          "BBSL1086801",
                                          "BBSL1086641",
                                          "BBSL1085741",
                                          "BBSL1085327",
                                          "BBSL1086773",
                                          "BBSL1071541",
                                          "BBSL1071540",
                                          "BBSL1071350",
                                          "BBSL1058229",
                                          "BBSL1071515",
                                          "BBSL1071439",
                                          "BBSL1071447",
                                          "BBSL1073200",
                                          "BBSL1071156",
                                          "BBSL1071609",
                                          "BBSL1071523",
                                          "BBSL1070203",
                                          "BBSL1058554",
                                          "BBSL1058202",
                                          "BBSL1071374",
                                          "BBSL1073952",
                                          "BBSL1070361",
                                          "BBSL1073198",
                                          "BBSL1074435",
                                          "BBSL1071360",
                                          "BBSL1070212",
                                          "BBSL1059274",
                                          "BBSL1071316",
                                          "BBSL1073290")),


    Heterosarus_bakeri_m= list(Genus="Heterosarus",
                               SubGenus ="",
                               Species="bakeri",
                               SubSpecies="",
                               Sex="m",
                               Author = "Cockerell",
                               Determiner="D. Yanega",
                               temp.id= c("BBSL1085401",
                                          "BBSL1084825",
                                          "BBSL1085037",
                                          "BBSL1084978",
                                          "BBSL1086425",
                                          "BBSL1086426",
                                          "BBSL1085343",
                                          "BBSL1086519",
                                          "BBSL1085400",
                                          "BBSL1085456",
                                          "BBSL1086435",
                                          "BBSL1086594",
                                          "BBSL1084750",
                                          "BBSL1084743",
                                          "BBSL1086784",
                                          "BBSL1086795",
                                          "BBSL1086804",
                                          "BBSL1086796",
                                          "BBSL1085993",
                                          "BBSL1073169",
                                          "BBSL1073201",
                                          "BBSL1073203",
                                          "BBSL1071231",
                                          "BBSL1071236",
                                          "BBSL1071158",
                                          "BBSL1071150",
                                          "BBSL1071230",
                                          "24747")),




    Heterosarus_neomex_f= list(Genus="Heterosarus",
                               SubGenus ="",
                               Species="neomexicanus",
                               SubSpecies="",
                               Sex="f",
                               Author = "Cockerell",
                               Determiner="D. Yanega",
                               temp.id= c("BBSL1086541",
                                          "BBSL1085767",
                                          "BBSL1086531",
                                          "BBSL1085125",
                                          "BBSL1086640",
                                          "BBSL1085691",
                                          "BBSL1086532",
                                          "BBSL1086809",
                                          "BBSL1085793",
                                          "BBSL1086630",
                                          "BBSL1086823",
                                          "BBSL1073148",
                                          "BBSL1071670",
                                          "BBSL1085481",
                                          "BBSL1085764", "23154"
                                          )),



    Heterosarus_neomex_m= list(Genus="Heterosarus",
                               SubGenus ="",
                               Species="neomexicanus",
                               SubSpecies="",
                               Sex="m",
                               Author = "Cockerell",
                               Determiner="D. Yanega",
                               temp.id= c(
                                   "BBSL1085484",
                                   "BBSL1085091",
                                   "BBSL1085335",
                                   "BBSL1073234",
                                   "BBSL1085177",
                                   "BBSL1085410",
                                   "BBSL1086818",
                                   "BBSL1085742",
                                   "BBSL1086802",
                                   "BBSL1085417",
                                   "BBSL1059160",
                                   "BBSL1059089",
                                   "BBSL1073166",
                                   "BBSL1073197",
                                   "BBSL1073199",
                                   "BBSL1074088"
                               )),

    
    Perdita_fallax_m= list(Genus="Perdita",
                           SubGenus="Perdita",
                           Species="fallax",
                           SubSpecies="", Sex="m",
                           Author = "Cockerell",
                           Determiner="T.  Griswold",
                           temp.id= c("BBSL1072966",
                                      "BBSL1072873",
                                      "BBSL1072611",
                                      "BBSL1072811",
                                      "BBSL1072191",
                                      "BBSL1072082",
                                      "BBSL1072150")),

    Perdita_fallax_f= list(Genus="Perdita",
                           SubGenus="Perdita",
                           Species="fallax",
                           SubSpecies="", Sex="f",
                           Author = "Cockerell",
                           Determiner="T.  Griswold",
                           temp.id= c("BBSL1073391",
                                      "BBSL1073106",
                                      "BBSL1072168",
                                      "BBSL1072712",
                                      "BBSL1070480",
                                      "BBSL1072293",
                                      "BBSL1070466",
                                      "BBSL1072064",
                                      "BBSL1072725",
                                      "BBSL1072700",
                                      "BBSL1072065",
                                      "BBSL1072143",
                                      "BBSL1072151")),

    Perdita_sp2= list(Genus="Perdita",
                      SubGenus="Perdita",
                      Species="sp. 2",
                      SubSpecies="", Sex="f",
                      Author = "",
                      Determiner="T.  Griswold",
                      temp.id= c("BBSL1072169")),


    Perdita_ignota_m= list(Genus="Perdita",
                           SubGenus="Hexaperdita",
                           Species="ignota",
                           SubSpecies="isopappi", Sex="m",
                           Author = "Cockerell",
                           Determiner="T.  Griswold","J.L. Neff",
                           temp.id= c("BBSL1071955","23141")),

        Perdita_ignota_f= list(Genus="Perdita",
                           SubGenus="Hexaperdita",
                           Species="ignota",
                           SubSpecies="isopappi", Sex="f",
                           Author = "Cockerell",
                           Determiner="J.L. Neff",
                           temp.id= c("23152")),

    Perdita_callicerata_m= list(Genus="Perdita",
                                SubGenus="Hexaperdita",
                                Species="callicerata",
                                SubSpecies="", Sex="m",
                                Author = "Cockerell",
                                Determiner="T.  Griswold",
                                temp.id= c("BBSL1072699")),


    Perdita_coreopsidis_f= list(Genus="Perdita",
                                SubGenus="Cockerellia",
                                Species="coreopsidis",
                                SubSpecies="collaris", Sex="f",
                                Author = "Cockerell",
                                Determiner="T.  Griswold",
                                temp.id= c("BBSL1072084")),

    Perdita_affinis_m= list(Genus="Perdita",
                                SubGenus="",
                                Species="affinis",
                                SubSpecies="", Sex="m",
                                Author = "Cresson",
                                Determiner="J.L. Neff",
                                temp.id= c("23060", "23584", "22593", 
                                           "21421", "21448", "22596", 
                                           "20816")),   

    Perdita_affinis_f= list(Genus="Perdita",
                                SubGenus="",
                                Species="affinis",
                                SubSpecies="", Sex="f",
                                Author = "Cresson",
                                Determiner="J.L. Neff",
                                temp.id= c("22597", "22543", "21384", 
                                           "22721", "21452", "23539", 
                                           "23529", "21395", "23596", 
                                           "23581", "23582", "23444", 
                                           "23418", "22595", "24972", 
                                           "23528", "21454", "23540", 
                                           "21424", "24973", "22732", 
                                           "21388", "22598", "22324", 
                                           "21371", "22722")),   

    Perdita_sexmaculata_f= list(Genus="Perdita",
                                SubGenus="",
                                Species="sexmaculata",
                                SubSpecies="", Sex="f",
                                Author = "Cockerell",
                                Determiner="J.L. Neff",
                                temp.id= c("21397", "21431")),   

    Andrena_costillensis= list(Genus="Andrena", SubGenus ="Cnemidandrena",
                               Species="costillensis", SubSpecies="",
                               Sex="f",
                               Author =
                                   "Viereck \\& Cockerell",
                               Determiner="T. Griswold",
                               temp.id= c("BBSL1071778",
                                          "BBSL1071824",
                                          "BBSL1071785",
                                          "BBSL1071763",
                                          "BBSL1071784")),

    Andrena_costillensis= list(Genus="Andrena", SubGenus ="Cnemidandrena",
                               Species="costillensis", SubSpecies="",
                               Sex="m",
                               Author =
                                   "Viereck \\& Cockerell",
                               Determiner="T. Griswold",
                               temp.id= c("BBSL1070619")),

    Andrena_birtwelli_f= list(Genus="Andrena", SubGenus ="Cnemidandrena",
                              Species="birtwelli", SubSpecies="",
                              Sex="f",
                              Author =
                                  "Cockerell",
                              Determiner="T. Griswold","J.L. Neff",
                              temp.id= c("BBSL1060020",
                                         "BBSL1060034",
                                         "BBSL1060011",
                                         "BBSL1060033",
                                         "BBSL1058720",
                                         "BBSL1059901",
                                         "BBSL1058733",
                                         "BBSL1058718",
                                         "BBSL1060010",
                                         "BBSL1060035",
                                         "BBSL1071063", "23087")),

    Andrena_birtwelli_m= list(Genus="Andrena", SubGenus ="Cnemidandrena",
                              Species="birtwelli", SubSpecies="",
                              Sex="m",
                              Author =
                                  "Cockerell",
                              Determiner="T. Griswold",
                              temp.id= c("BBSL1060009",
                                         "BBSL1070662")),


    Andrena_columbiana= list(Genus="Andrena", SubGenus ="Cnemidandrena",
                             Species="columbiana", SubSpecies="",
                             Sex="f",
                             Author =
                                 "Viereck",
                             Determiner="T. Griswold",
                             temp.id= c("BBSL1071936")),

    ## Stylopized
    Andrena_sp1= list(Genus="Andrena", SubGenus ="Cnemidandrena",
                      Species="sp.", SubSpecies="1",
                      Sex="f",
                      Author ="",
                      Determiner="T. Griswold",
                      temp.id= c("BBSL1070337")),

    Andrena_sp1= list(Genus="Andrena", SubGenus ="Cnemidandrena",
                      Species="sp.", SubSpecies="1",
                      Sex="m",
                      Author ="",
                      Determiner="T. Griswold",
                      temp.id= c("BBSL1071777")),

    Andrena_sp2= list(Genus="Andrena", SubGenus ="Andrena ",
                      Species="sp.", SubSpecies="2",
                      Sex="m",
                      Author ="",
                      Determiner="T. Griswold",
                      temp.id= c("BBSL1073129"))







)
