
sp.ids <- list(
    
    
    Hylaeus_mesillae = list(Genus="Hylaeus", SubGenus ="Hylaeus",
                            Species="mesillae", SubSpecies="",
                            Sex="m",
                            Author = "Cockerell",
                            Determiner="T. Griswold",
                            temp.id= c("BBSL1087259")),
    
    
    Hylaeus_wootoni = list(Genus="Hylaeus", SubGenus ="Hylaeus",
                           Species="wootoni", SubSpecies="",
                           Sex="f",
                           Author = "Cockerell",
                           Determiner="T. Griswold",
                           temp.id= c("BBSL1071450",
                                      "BBSL1071440",
                                      "BBSL1071332",
                                      "BBSL1071420",
                                      "BBSL1071335",
                                      "BBSL1071572",
                                      "BBSL1070661",
                                      "BBSL1070659",
                                      "BBSL1071233",
                                      "BBSL1071571",
                                      "BBSL1071449",
                                      "BBSL1071448",
                                      "BBSL1071503",
                                      "BBSL1071504",
                                      "BBSL1058525",
                                      "BBSL1059158",
                                      "BBSL1058478",
                                      "BBSL1058553",
                                      "BBSL1086436",
                                      "BBSL1085606",
                                      "BBSL1086502")),
    
    Hylaeus_wootoni = list(Genus="Hylaeus", SubGenus ="Hylaeus",
                           Species="wootoni", SubSpecies="",
                           Sex="m",
                           Author = "Cockerell",
                           Determiner="T. Griswold",
                           temp.id= c("BBSL1058518",
                                      "BBSL1085324")),
    
    Hylaeus_personatellus = list(Genus="Hylaeus", SubGenus ="Hylaeus",
                           Species="personatellus", SubSpecies="",
                           Sex="m",
                           Author = "Cockerell",
                           Determiner="T. Griswold",
                           temp.id= c("BBSL1071161")),

    
    Colletes_hyalinus = list(Genus="Colletes", SubGenus ="",
                                 Species="hyalinus", SubSpecies="hyalinus",
                                 Sex="m",
                                 Author = "Provancher",
                                 Determiner="T. Griswold",
                                 temp.id= c("BBSL1085803")),
    

    Colletes_sp1_m= list(Genus="Colletes", SubGenus ="",
                             Species="sp.", SubSpecies="1", Sex="m", Author = "",
                             Determiner="T. Griswold",
                             temp.id= c("BBSL1071075")),
    
    Colletes_sp2_m= list(Genus="Colletes", SubGenus ="",
                         Species="sp.", SubSpecies="2", Sex="m", Author = "",
                         Determiner="T. Griswold",
                         temp.id= c("BBSL1073355", "BBSL1084432")),
    
    Colletes_sp3_m= list(Genus="Colletes", SubGenus ="",
                         Species="sp.", SubSpecies="3", Sex="m", Author = "",
                         Determiner="T. Griswold",
                         temp.id= c("BBSL1072880")),
    
    
 Colletes_slevini_m= list(Genus="Colletes", SubGenus ="",
    Species="slevini", SubSpecies="", Sex="m", Author = "Cockerell",
    Determiner="T. Griswold",
    temp.id= c("BBSL1058839", "BBSL1073216")),


    Colletes_skinneri_m= list(Genus="Colletes", SubGenus ="",
                              Species="skinneri", SubSpecies="", Sex="m",
                              Author = "Viereck",
                              Determiner="D. Yanega",
                              temp.id= c("BBSL1073256",
                                         "BBSL1073240",
                                         "BBSL1073257",
                                         "BBSL1073241",
                                         "BBSL1073258")),

    Colletes_compactus_m = list(Genus="Colletes", SubGenus ="",
                                Species="compactus", SubSpecies="", Sex="m",
                                Author = "Cresson",
                                Determiner = "T. Griswold",
                                temp.id= c("BBSL1073193", "BBSL1073266",
                                           "BBSL1073267", "BBSL1073268",
                                           "BBSL1073269", "BBSL1073270",
                                           "BBSL1073273", "BBSL1073274",
                                           "BBSL1073277", "BBSL1073278",
                                           "BBSL1073281", "BBSL1073215",
                                           "BBSL1073284", "BBSL1073286",
                                           "BBSL1073291", "BBSL1073292",
                                           "BBSL1073293", "BBSL1073294",
                                           "BBSL1073295", "BBSL1073296",
                                           "BBSL1073297")),

    Colletes_nigrifrons_f = list(Genus="Colletes", SubGenus ="",
                                 Species="nigrifrons", SubSpecies="",
                                 Sex="f",
                                 Author = "Titus", Determiner = "T. Griswold",
                                 temp.id= c("BBSL1058717",
                                            "BBSL1058680",
                                            "BBSL1071022",
                                            "BBSL1071049",
                                            "BBSL1071052",
                                            "BBSL1071077",
                                            "BBSL1071087",
                                            "BBSL1071097",
                                            "BBSL1071101",
                                            "BBSL1071102",
                                            "BBSL1071109",
                                            "BBSL1071043",
                                            "BBSL1071090",
                                            "BBSL1071091",
                                            "BBSL1071116",
                                            "BBSL1071071",
                                            "BBSL1071076",
                                            "BBSL1071079",
                                            "BBSL1071080",
                                            "BBSL1071089",
                                            "BBSL1084762")),

 Colletes_scopiventer_f = list(Genus="Colletes", SubGenus ="Consors",
                               Species="scopiventer", SubSpecies="",
                               Sex="f",
                               Author = "Swenk",
                               Determiner = "T. Griswold",
                               temp.id= c("BBSL1070461")),

 Colletes_lutzi_f = list(Genus="Colletes", SubGenus ="Hyalinus",
                         Species="lutzi", SubSpecies="lutzi", Sex="f",
                         Author = "Timberlake",
                         Determiner = "T. Griswold",
                         temp.id= c("BBSL1070634")),

 Colletes_phaceliae_f = list(Genus="Colletes", SubGenus ="Hyalinus",
                             Species="phaceliae", SubSpecies="",
                             Sex="f",
                             Author = "Cockerell",
                             Determiner = "T. Griswold",
                             temp.id= c("BBSL1071104", "BBSL1071069")),

 Colletes_gilensis_m= list(Genus="Colletes", SubGenus ="",
                           Species="gilensis", SubSpecies="",
                           Sex="m",
                           Author = "Cockerell",
                           Determiner = "T. Griswold",
                           temp.id= c("BBSL1074274", "BBSL1059883",
                                      "BBSL1059170", "BBSL1059258")),

 Colletes_gilensis_f= list(Genus="Colletes", SubGenus ="Productus",
                           Species="gilensis", SubSpecies="",
                           Sex="f",
                           Author = "Cockerell",
                           Determiner = "T. Griswold",
                           temp.id= c("BBSL1070592")),

 Colletes_eulophi_f = list(Genus="Colletes", SubGenus ="",
                           Species="eulophi", SubSpecies="", Sex="f",
                           Author = "Robertson", Determiner = "T. Griswold",
                           temp.id= c("BBSL1072848", "BBSL1074423")),

 Colletes_wootoni_f = list(Genus="Colletes", SubGenus ="",
                           Species="wootoni", SubSpecies="", Sex="f",
                           Author = "Cockerell",
                           Determiner = "T. Griswold",
                           temp.id= c("BBSL1070927", "BBSL1060049")),

 Hylaeus_annulatus_f = list(Genus="Hylaeus", SubGenus ="Hylaeus",
                            Species="annulatus", SubSpecies="",
                            Sex="f",
                            Author = "Linnaeus",
                            Determiner = "T. Griswold",
                            temp.id= c( "BBSL1071355",
                                       "BBSL1071941", "BBSL1071896",
                                       "BBSL1070593", "BBSL1071485",
                                       "BBSL1071419",
                                       "BBSL1071465", "BBSL1058270",
                                       "BBSL1058539",
                                       "BBSL1058291", "BBSL1058521",
                                       "BBSL1058344","BBSL1058462",
                                       "BBSL1058374", "BBSL1058517",
                                       "BBSL1058450",
                                       "BBSL1058280",
                                       "BBSL1058526", "BBSL1058477",
                                       "BBSL1071642",
                                       "BBSL1086528", "BBSL1086698",
                                       "BBSL1086695", "BBSL1086705",
                                       "BBSL1084714", "BBSL1085355",
                                       "BBSL1086547", "BBSL1085273",
                                       "BBSL1086556", "BBSL1086492",
                                       "BBSL1084607", "BBSL1071633",
                                       "BBSL1086533")),

 Hylaeus_annulatus_f = list(Genus="Hylaeus", SubGenus ="Hylaeus",
                            Species="annulatus", SubSpecies="",
                            Sex="f",
                            Author = "Linnaeus",
                            Determiner = "J.L. Neff",
                            temp.id= c("23000","23449")),

 Hylaeus_annulatus_m = list(Genus="Hylaeus", SubGenus ="Hylaeus",
                            Species="annulatus", SubSpecies="",
                            Sex="m",
                            Author = "Linnaeus",
                            Determiner = "T. Griswold",
                            temp.id= c("BBSL1058282",
                                       "BBSL1084628",
                                       "BBSL1084606")),

 Hylaeus_basalis_f = list(Genus="Hylaeus", SubGenus ="Cephalylaeus",
                          Species="basalis", SubSpecies="", Sex="f",
                          Author = "Smith",
                          Determiner = "T. Griswold",
                          temp.id= c("BBSL1058725", "BBSL1058671"))




)
